name: katana_localization_annotation
description: Define annotations to use the Katana localization builder. Build with katana_localization_builder using this annotation.
version: 3.1.6
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/katana_localization_annotation

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  katana: ^3.2.1
dev_dependencies:
  test: ^1.25.0
  katana_test: ^3.0.3
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0
