/// Contents of localize.base.yaml.
///
/// localize.base.yamlの中身。
String localizeYamlCode() => """
localize:
  # Words
  - key: "Yes"
    en_US: "Yes"
    ja_JP: "はい"
    zh_CN: "是的"
    ko_KR: "예"
    es_ES: "Sí"
    fr_FR: "Oui"
    de_DE: "Ja"
    pt_PT: "Sim"
    ru_RU: "Да"
    id_ID: "Ya"
  - key: "No"
    en_US: "No"
    ja_JP: "いいえ"
    zh_CN: "不"
    ko_KR: "아니요"
    es_ES: "No"
    fr_FR: "Non"
    de_DE: "Nein"
    pt_PT: "Não"
    ru_RU: "Нет"
    id_ID: "Tidak"
  - key: "OK"
    en_US: "Okay"
    ja_JP: "OK"
    zh_CN: "好的"
    ko_KR: "좋아요"
    es_ES: "OK"
    fr_FR: "OK"
    de_DE: "OK"
    pt_PT: "OK"
    ru_RU: "OK"
    id_ID: "OK"
  - key: "Open"
    en_US: "Open"
    ja_JP: "開く"
    zh_CN: "打开"
    ko_KR: "열려 있는"
    es_ES: "Abrir"
    fr_FR: "Ouvrir"
    de_DE: "Öffnen"
    pt_PT: "Abrir"
    ru_RU: "Открыть"
    id_ID: "Buka"
  - key: "Close"
    en_US: "Close"
    ja_JP: "閉じる"
    zh_CN: "关闭"
    ko_KR: "닫다"
    es_ES: "Cerrar"
    fr_FR: "Fermer"
    de_DE: "Schließen"
    pt_PT: "Fechar"
    ru_RU: "Закрыть"
    id_ID: "Tutup"
  - key: "Forward"
    en_US: "Forward"
    ja_JP: "進む"
    zh_CN: "继续前行"
    ko_KR: "계속 움직입니다"
    es_ES: "Adelante"
    fr_FR: "En avant"
    de_DE: "Vorwärts"
    pt_PT: "Avançar"
    ru_RU: "Вперед"
    id_ID: "Maju"
  - key: "Back"
    en_US: "Back"
    ja_JP: "戻る"
    zh_CN: "返回"
    ko_KR: "반품"
    es_ES: "Atrás"
    fr_FR: "Retour"
    de_DE: "Zurück"
    pt_PT: "Voltar"
    ru_RU: "Назад"
    id_ID: "Kembali"
  - key: "Next"
    en_US: "Next"
    ja_JP: "次"
    zh_CN: "下一个"
    ko_KR: "다음"
    es_ES: "Siguiente"
    fr_FR: "Suivant"
    de_DE: "Weiter"
    pt_PT: "Próximo"
    ru_RU: "Далее"
    id_ID: "Berikutnya"
  - key: "Prev"
    en_US: "Prev"
    ja_JP: "前"
    zh_CN: "前"
    ko_KR: "전에"
    es_ES: "Anterior"
    fr_FR: "Précédent"
    de_DE: "Zurück"
    pt_PT: "Anterior"
    ru_RU: "Предыдущий"
    id_ID: "Sebelumnya"
  - key: "To Next"
    en_US: "Next"
    ja_JP: "次へ"
    zh_CN: "到下一个"
    ko_KR: "다음"
    es_ES: "Siguiente"
    fr_FR: "Suivant"
    de_DE: "Weiter"
    pt_PT: "Próximo"
    ru_RU: "Далее"
    id_ID: "Berikutnya"
  - key: "To Prev"
    en_US: "Prev"
    ja_JP: "前へ"
    zh_CN: "以前的"
    ko_KR: "이전"
    es_ES: "Anterior"
    fr_FR: "Précédent"
    de_DE: "Zurück"
    pt_PT: "Anterior"
    ru_RU: "Предыдущий"
    id_ID: "Sebelumnya"
  - key: "Skip"
    en_US: "Skip"
    ja_JP: "スキップ"
    zh_CN: "跳过"
    ko_KR: "건너뛰다"
    es_ES: "Omitir"
    fr_FR: "Ignorer"
    de_DE: "Überspringen"
    pt_PT: "Pular"
    ru_RU: "Пропустить"
    id_ID: "Lewati"
  - key: "Result"
    en_US: "Result"
    ja_JP: "結果"
    zh_CN: "结果"
    ko_KR: "결과"
    es_ES: "Resultado"
    fr_FR: "Résultat"
    de_DE: "Ergebnis"
    pt_PT: "Resultado"
    ru_RU: "Результат"
    id_ID: "Hasil"
  - key: "Done"
    en_US: "Done"
    ja_JP: "完了"
    zh_CN: "完成"
    ko_KR: "완성"
    es_ES: "Listo"
    fr_FR: "Terminé"
    de_DE: "Fertig"
    pt_PT: "Feito"
    ru_RU: "Готово"
    id_ID: "Selesai"
  - key: "Complete"
    en_US: "Complete"
    ja_JP: "完了"
    zh_CN: "完成"
    ko_KR: "완성"
    es_ES: "Completo"
    fr_FR: "Complet"
    de_DE: "Vollständig"
    pt_PT: "Completo"
    ru_RU: "Завершить"
    id_ID: "Lengkap"
  - key: "None"
    en_US: "None"
    ja_JP: "なし"
    zh_CN: "没有任何"
    ko_KR: "없음"
    es_ES: "Ninguno"
    fr_FR: "Aucun"
    de_DE: "Keine"
    pt_PT: "Nenhum"
    ru_RU: "Нет"
    id_ID: "Tidak ada"
  - key: "Success"
    en_US: "Success"
    ja_JP: "成功"
    zh_CN: "成功"
    ko_KR: "성공"
    es_ES: "Éxito"
    fr_FR: "Succès"
    de_DE: "Erfolg"
    pt_PT: "Sucesso"
    ru_RU: "Успех"
    id_ID: "Sukses"
  - key: "Error"
    en_US: "Error"
    ja_JP: "エラー"
    zh_CN: "错误"
    ko_KR: "오류"
    es_ES: "Error"
    fr_FR: "Erreur"
    de_DE: "Fehler"
    pt_PT: "Erro"
    ru_RU: "Ошибка"
    id_ID: "Kesalahan"
  - key: "Warning"
    en_US: "Warning"
    ja_JP: "警告"
    zh_CN: "警告"
    ko_KR: "경고"
    es_ES: "Advertencia"
    fr_FR: "Avertissement"
    de_DE: "Warnung"
    pt_PT: "Aviso"
    ru_RU: "Предупреждение"
    id_ID: "Peringatan"
  - key: "Notice"
    en_US: "Notice"
    ja_JP: "注意"
    zh_CN: "笔记"
    ko_KR: "메모"
    es_ES: "Aviso"
    fr_FR: "Avis"
    de_DE: "Hinweis"
    pt_PT: "Aviso"
    ru_RU: "Уведомление"
    id_ID: "Pemberitahuan"
  - key: "Confirm"
    en_US: "Confirm"
    ja_JP: "決定"
    zh_CN: "决定"
    ko_KR: "결정"
    es_ES: "Confirmar"
    fr_FR: "Confirmer"
    de_DE: "Bestätigen"
    pt_PT: "Confirmar"
    ru_RU: "Подтвердить"
    id_ID: "Konfirmasi"
  - key: "Decision"
    en_US: "Decision"
    ja_JP: "確定"
    zh_CN: "确认"
    ko_KR: "확인하다"
    es_ES: "Decisión"
    fr_FR: "Décision"
    de_DE: "Entscheidung"
    pt_PT: "Decisão"
    ru_RU: "Решение"
    id_ID: "Keputusan"
  - key: "Cancel"
    en_US: "Cancel"
    ja_JP: "キャンセル"
    zh_CN: "取消"
    ko_KR: "취소"
    es_ES: "Cancelar"
    fr_FR: "Annuler"
    de_DE: "Abbrechen"
    pt_PT: "Cancelar"
    ru_RU: "Отменить"
    id_ID: "Batal"
  - key: "Confirmation"
    en_US: "Confirmation"
    ja_JP: "確認"
    zh_CN: "确认"
    ko_KR: "확인"
    es_ES: "Confirmación"
    fr_FR: "Confirmation"
    de_DE: "Bestätigung"
    pt_PT: "Confirmação"
    ru_RU: "Подтверждение"
    id_ID: "Konfirmasi"
  - key: "Refresh"
    en_US: "Refresh"
    ja_JP: "更新"
    zh_CN: "更新"
    ko_KR: "업데이트"
    es_ES: "Actualizar"
    fr_FR: "Actualiser"
    de_DE: "Aktualisieren"
    pt_PT: "Atualizar"
    ru_RU: "Обновить"
    id_ID: "Menyegarkan"
  - key: "Update"
    en_US: "Update"
    ja_JP: "更新"
    zh_CN: "更新"
    ko_KR: "업데이트"
    es_ES: "Actualizar"
    fr_FR: "Mettre à jour"
    de_DE: "Aktualisieren"
    pt_PT: "Atualizar"
    ru_RU: "Обновить"
    id_ID: "Memperbarui"
  - key: "Change"
    en_US: "Change"
    ja_JP: "変更"
    zh_CN: "改变"
    ko_KR: "변화"
    es_ES: "Cambiar"
    fr_FR: "Changer"
    de_DE: "Ändern"
    pt_PT: "Alterar"
    ru_RU: "Изменить"
    id_ID: "Mengubah"
  - key: "Send"
    en_US: "Send"
    ja_JP: "送信"
    zh_CN: "发送"
    ko_KR: "보내다"
    es_ES: "Enviar"
    fr_FR: "Envoyer"
    de_DE: "Senden"
    pt_PT: "Enviar"
    ru_RU: "Отправить"
    id_ID: "Kirim"
  - key: "Resend"
    en_US: "Resend"
    ja_JP: "再送信"
    zh_CN: "重新传播"
    ko_KR: "재전송"
    es_ES: "Reenviar"
    fr_FR: "Renvoyer"
    de_DE: "Erneut senden"
    pt_PT: "Reenviar"
    ru_RU: "Переслать"
    id_ID: "Kirim ulang"
  - key: "Retry"
    en_US: "Retry"
    ja_JP: "リトライ"
    zh_CN: "重试"
    ko_KR: "다시 해 보다"
    es_ES: "Reintentar"
    fr_FR: "Réessayer"
    de_DE: "Wiederholen"
    pt_PT: "Tentar novamente"
    ru_RU: "Повторить"
    id_ID: "Coba lagi"
  - key: "Quit"
    en_US: "Quit"
    ja_JP: "終了"
    zh_CN: "结尾"
    ko_KR: "끝"
    es_ES: "Salir"
    fr_FR: "Quitter"
    de_DE: "Beenden"
    pt_PT: "Sair"
    ru_RU: "Выйти"
    id_ID: "Keluar"
  - key: "Property"
    en_US: "Property"
    ja_JP: "プロパティ"
    zh_CN: "财产"
    ko_KR: "재산"
    es_ES: "Propiedad"
    fr_FR: "Propriété"
    de_DE: "Eigenschaft"
    pt_PT: "Propriedade"
    ru_RU: "Свойство"
    id_ID: "Properti"
  - key: "All Day"
    en_US: "All day"
    ja_JP: "終日"
    zh_CN: "一整天"
    ko_KR: "하루 종일"
    es_ES: "Todo el día"
    fr_FR: "Toute la journée"
    de_DE: "Ganztägig"
    pt_PT: "O dia todo"
    ru_RU: "Весь день"
    id_ID: "Sepanjang hari"
  - key: "Others"
    en_US: "Others"
    ja_JP: "その他"
    zh_CN: "其他的"
    ko_KR: "기타"
    es_ES: "Otros"
    fr_FR: "Autres"
    de_DE: "Andere"
    pt_PT: "Outros"
    ru_RU: "Другие"
    id_ID: "Lainnya"
  - key: "Note"
    en_US: "Note"
    ja_JP: "ノート"
    zh_CN: "笔记"
    ko_KR: "메모"
    es_ES: "Nota"
    fr_FR: "Note"
    de_DE: "Notiz"
    pt_PT: "Nota"
    ru_RU: "Заметка"
    id_ID: "Catatan"
  - key: "Process"
    en_US: "Process"
    ja_JP: "処理"
    zh_CN: "过程"
    ko_KR: "프로세스"
    es_ES: "Proceso"
    fr_FR: "Processus"
    de_DE: "Prozess"
    pt_PT: "Processo"
    ru_RU: "Процесс"
    id_ID: "Proses"
  - key: "Detail"
    en_US: "Detail"
    ja_JP: "詳細"
    zh_CN: "细节"
    ko_KR: "세부 사항"
    es_ES: "Detalle"
    fr_FR: "Détail"
    de_DE: "Detail"
    pt_PT: "Detalhe"
    ru_RU: "Деталь"
    id_ID: "Detail"
  - key: "Setting"
    en_US: "Setting"
    ja_JP: "設定"
    zh_CN: "环境"
    ko_KR: "환경"
    es_ES: "Configuración"
    fr_FR: "Paramètre"
    de_DE: "Einstellung"
    pt_PT: "Configuração"
    ru_RU: "Настройка"
    id_ID: "Pengaturan"
  - key: "Config"
    en_US: "Config"
    ja_JP: "設定"
    zh_CN: "环境"
    ko_KR: "환경"
    es_ES: "Configuración"
    fr_FR: "Configuration"
    de_DE: "Konfiguration"
    pt_PT: "Configuração"
    ru_RU: "Конфигурация"
    id_ID: "Konfigurasi"
  - key: "Post"
    en_US: "Post"
    ja_JP: "投稿"
    zh_CN: "发布"
    ko_KR: "전기"
    es_ES: "Publicar"
    fr_FR: "Publier"
    de_DE: "Veröffentlichen"
    pt_PT: "Publicar"
    ru_RU: "Опубликовать"
    id_ID: "Pos"
  - key: "Submit"
    en_US: "Submit"
    ja_JP: "決定"
    zh_CN: "决定"
    ko_KR: "결정"
    es_ES: "Enviar"
    fr_FR: "Soumettre"
    de_DE: "Einreichen"
    pt_PT: "Enviar"
    ru_RU: "Отправить"
    id_ID: "Kirim"
  - key: "Create"
    en_US: "Create"
    ja_JP: "作成"
    zh_CN: "创造"
    ko_KR: "만들다"
    es_ES: "Crear"
    fr_FR: "Créer"
    de_DE: "Erstellen"
    pt_PT: "Criar"
    ru_RU: "Создать"
    id_ID: "Membuat"
  - key: "Register"
    en_US: "Register"
    ja_JP: "登録"
    zh_CN: "登记"
    ko_KR: "등록하다"
    es_ES: "Registrar"
    fr_FR: "S'inscrire"
    de_DE: "Registrieren"
    pt_PT: "Registrar"
    ru_RU: "Зарегистрировать"
    id_ID: "Daftar"
  - key: "Registration"
    en_US: "Registration"
    ja_JP: "登録"
    zh_CN: "登记"
    ko_KR: "등록하다"
    es_ES: "Registro"
    fr_FR: "Inscription"
    de_DE: "Registrierung"
    pt_PT: "Registro"
    ru_RU: "Регистрация"
    id_ID: "Pendaftaran"
  - key: "Save"
    en_US: "Save"
    ja_JP: "保存"
    zh_CN: "保持"
    ko_KR: "유지하다"
    es_ES: "Guardar"
    fr_FR: "Sauvegarder"
    de_DE: "Speichern"
    pt_PT: "Salvar"
    ru_RU: "Сохранить"
    id_ID: "Simpan"
  - key: "Data"
    en_US: "Data"
    ja_JP: "データ"
    zh_CN: "数据"
    ko_KR: "데이터"
    es_ES: "Datos"
    fr_FR: "Données"
    de_DE: "Daten"
    pt_PT: "Dados"
    ru_RU: "Данные"
    id_ID: "Data"
  - key: "Fetch"
    en_US: "Fetch"
    ja_JP: "取得"
    zh_CN: "获得"
    ko_KR: "인수"
    es_ES: "Obtener"
    fr_FR: "Récupérer"
    de_DE: "Abrufen"
    pt_PT: "Buscar"
    ru_RU: "Получить"
    id_ID: "Ambil"
  - key: "Add"
    en_US: "Add"
    ja_JP: "追加"
    zh_CN: "添加"
    ko_KR: "덧셈"
    es_ES: "Agregar"
    fr_FR: "Ajouter"
    de_DE: "Hinzufügen"
    pt_PT: "Adicionar"
    ru_RU: "Добавить"
    id_ID: "Menambahkan"
  - key: "Edit"
    en_US: "Edit"
    ja_JP: "編集"
    zh_CN: "编辑"
    ko_KR: "편집하다"
    es_ES: "Editar"
    fr_FR: "Modifier"
    de_DE: "Bearbeiten"
    pt_PT: "Editar"
    ru_RU: "Редактировать"
    id_ID: "Sunting"
  - key: "Remove"
    en_US: "Remove"
    ja_JP: "削除"
    zh_CN: "删除"
    ko_KR: "삭제"
    es_ES: "Eliminar"
    fr_FR: "Supprimer"
    de_DE: "Entfernen"
    pt_PT: "Remover"
    ru_RU: "Удалить"
    id_ID: "Menghapus"
  - key: "Delete"
    en_US: "Delete"
    ja_JP: "削除"
    zh_CN: "删除"
    ko_KR: "삭제"
    es_ES: "Eliminar"
    fr_FR: "Supprimer"
    de_DE: "Löschen"
    pt_PT: "Excluir"
    ru_RU: "Удалить"
    id_ID: "Hapus"
  - key: "Join"
    en_US: "Join"
    ja_JP: "参加"
    zh_CN: "参与"
    ko_KR: "참여"
    es_ES: "Unirse"
    fr_FR: "Rejoindre"
    de_DE: "Beitreten"
    pt_PT: "Participar"
    ru_RU: "Присоединиться"
    id_ID: "Bergabung"
  - key: "Manage"
    en_US: "Manage"
    ja_JP: "管理"
    zh_CN: "管理"
    ko_KR: "관리"
    es_ES: "Gestionar"
    fr_FR: "Gérer"
    de_DE: "Verwalten"
    pt_PT: "Gerenciar"
    ru_RU: "Управлять"
    id_ID: "Mengelola"
  - key: "Management"
    en_US: "Management"
    ja_JP: "管理"
    zh_CN: "管理"
    ko_KR: "관리"
    es_ES: "Gestión"
    fr_FR: "Gestion"
    de_DE: "Verwaltung"
    pt_PT: "Gestão"
    ru_RU: "Управление"
    id_ID: "Manajemen"
  - key: "Search"
    en_US: "Search"
    ja_JP: "検索"
    zh_CN: "搜索"
    ko_KR: "찾다"
    es_ES: "Buscar"
    fr_FR: "Rechercher"
    de_DE: "Suchen"
    pt_PT: "Pesquisar"
    ru_RU: "Поиск"
    id_ID: "Cari"
  - key: "Article"
    en_US: "Article"
    ja_JP: "記事"
    zh_CN: "文章"
    ko_KR: "기사"
    es_ES: "Artículo"
    fr_FR: "Article"
    de_DE: "Artikel"
    pt_PT: "Artigo"
    ru_RU: "Статья"
    id_ID: "Artikel"
  - key: "Report"
    en_US: "Report"
    ja_JP: "通報"
    zh_CN: "报告"
    ko_KR: "보고서"
    es_ES: "Reportar"
    fr_FR: "Signaler"
    de_DE: "Melden"
    pt_PT: "Relatar"
    ru_RU: "Сообщить"
    id_ID: "Laporkan"
  - key: "DateTime"
    en_US: "DateTime"
    ja_JP: "日時"
    zh_CN: "时间日期"
    ko_KR: "일시"
    es_ES: "Fecha y hora"
    fr_FR: "Date et heure"
    de_DE: "Datum und Uhrzeit"
    pt_PT: "Data e hora"
    ru_RU: "Дата и время"
    id_ID: "Tanggal dan waktu"
  - key: "Review"
    en_US: "Review"
    ja_JP: "評価"
    zh_CN: "评估"
    ko_KR: "평가"
    es_ES: "Revisar"
    fr_FR: "Évaluer"
    de_DE: "Bewerten"
    pt_PT: "Revisar"
    ru_RU: "Отзыв"
    id_ID: "Ulasan"
  - key: "History"
    en_US: "History"
    ja_JP: "履歴"
    zh_CN: "历史"
    ko_KR: "이력"
    es_ES: "Historial"
    fr_FR: "Historique"
    de_DE: "Verlauf"
    pt_PT: "Histórico"
    ru_RU: "История"
    id_ID: "Riwayat"
  - key: "Buy"
    en_US: "Buy"
    ja_JP: "購入"
    zh_CN: "购买"
    ko_KR: "구매"
    es_ES: "Comprar"
    fr_FR: "Acheter"
    de_DE: "Kaufen"
    pt_PT: "Comprar"
    ru_RU: "Купить"
    id_ID: "Beli"
  - key: "Buying"
    en_US: "Buying"
    ja_JP: "購入"
    zh_CN: "购买"
    ko_KR: "구매"
    es_ES: "Comprando"
    fr_FR: "Achat"
    de_DE: "Kaufen"
    pt_PT: "Comprando"
    ru_RU: "Покупка"
    id_ID: "Membeli"
  - key: "Already bought"
    en_US: "Already bought"
    ja_JP: "購入済み"
    zh_CN: "已购买"
    ko_KR: "구매됨"
    es_ES: "Ya comprado"
    fr_FR: "Déjà acheté"
    de_DE: "Bereits gekauft"
    pt_PT: "Já comprado"
    ru_RU: "Уже куплено"
    id_ID: "Sudah dibeli"
  - key: "Already registered"
    en_US: "Already registered"
    ja_JP: "登録済み"
    zh_CN: "挂号的"
    ko_KR: "등록됨"
    es_ES: "Ya registrado"
    fr_FR: "Déjà enregistré"
    de_DE: "Bereits registriert"
    pt_PT: "Já registrado"
    ru_RU: "Уже зарегистрирован"
    id_ID: "Sudah terdaftar"
  - key: "Restore"
    en_US: "Restore"
    ja_JP: "復元"
    zh_CN: "恢复"
    ko_KR: "복원"
    es_ES: "Restaurar"
    fr_FR: "Restaurer"
    de_DE: "Wiederherstellen"
    pt_PT: "Restaurar"
    ru_RU: "Восстановить"
    id_ID: "Pulihkan"
  - key: "Public"
    en_US: "Public"
    ja_JP: "公開"
    zh_CN: "公开"
    ko_KR: "공개"
    es_ES: "Público"
    fr_FR: "Public"
    de_DE: "Öffentlich"
    pt_PT: "Público"
    ru_RU: "Публичный"
    id_ID: "Publik"
  - key: "Private"
    en_US: "Private"
    ja_JP: "非公開"
    zh_CN: "非公开"
    ko_KR: "비공개"
    es_ES: "Privado"
    fr_FR: "Privé"
    de_DE: "Privat"
    pt_PT: "Privado"
    ru_RU: "Частный"
    id_ID: "Pribadi"
  - key: "Agreement"
    en_US: "Agreement"
    ja_JP: "注意事項"
    zh_CN: "协议"
    ko_KR: "합의"
    es_ES: "Acuerdo"
    fr_FR: "Accord"
    de_DE: "Vereinbarung"
    pt_PT: "Acordo"
    ru_RU: "Соглашение"
    id_ID: "Perjanjian"
  - key: "Terms of Use"
    en_US: "Terms of Use"
    ja_JP: "利用規約"
    zh_CN: "使用条款"
    ko_KR: "이용약관"
    es_ES: "Términos de uso"
    fr_FR: "Conditions d'utilisation"
    de_DE: "Nutzungsbedingungen"
    pt_PT: "Termos de uso"
    ru_RU: "Условия использования"
    id_ID: "Syarat Penggunaan"
  - key: "Privacy Policy"
    en_US: "Privacy Policy"
    ja_JP: "プライバシーポリシー"
    zh_CN: "隐私政策"
    ko_KR: "개인 정보 보호 정책"
    es_ES: "Política de privacidad"
    fr_FR: "Politique de confidentialité"
    de_DE: "Datenschutzrichtlinie"
    pt_PT: "Política de privacidade"
    ru_RU: "Политика конфиденциальности"
    id_ID: "Kebijakan Privasi"
  - key: "User"
    en_US: "User"
    ja_JP: "ユーザー"
    zh_CN: "用户"
    ko_KR: "사용자"
    es_ES: "Usuario"
    fr_FR: "Utilisateur"
    de_DE: "Benutzer"
    pt_PT: "Usuário"
    ru_RU: "Пользователь"
    id_ID: "Pengguna"
  - key: "Contents"
    en_US: "Contents"
    ja_JP: "コンテンツ"
    zh_CN: "内容"
    ko_KR: "콘텐츠"
    es_ES: "Contenido"
    fr_FR: "Contenu"
    de_DE: "Inhalt"
    pt_PT: "Conteúdo"
    ru_RU: "Контент"
    id_ID: "Konten"
  - key: "Content"
    en_US: "Content"
    ja_JP: "コンテンツ"
    zh_CN: "内容"
    ko_KR: "콘텐츠"
    es_ES: "Contenido"
    fr_FR: "Contenu"
    de_DE: "Inhalt"
    pt_PT: "Conteúdo"
    ru_RU: "Контент"
    id_ID: "Konten"
  - key: "Favorite"
    en_US: "Favorite"
    ja_JP: "お気に入り"
    zh_CN: "最喜欢的"
    ko_KR: "가장 좋아하는"
    es_ES: "Favorito"
    fr_FR: "Favori"
    de_DE: "Favorit"
    pt_PT: "Favorito"
    ru_RU: "Избранное"
    id_ID: "Favorit"
  - key: "Member"
    en_US: "Member"
    ja_JP: "メンバー"
    zh_CN: "成员"
    ko_KR: "회원"
    es_ES: "Miembro"
    fr_FR: "Membre"
    de_DE: "Mitglied"
    pt_PT: "Membro"
    ru_RU: "Участник"
    id_ID: "Anggota"
  - key: "Message"
    en_US: "Message"
    ja_JP: "メッセージ"
    zh_CN: "信息"
    ko_KR: "메시지"
    es_ES: "Mensaje"
    fr_FR: "Message"
    de_DE: "Nachricht"
    pt_PT: "Mensagem"
    ru_RU: "Сообщение"
    id_ID: "Pesan"
  - key: "Title"
    en_US: "Title"
    ja_JP: "タイトル"
    zh_CN: "标题"
    ko_KR: "제목"
    es_ES: "Título"
    fr_FR: "Titre"
    de_DE: "Titel"
    pt_PT: "Título"
    ru_RU: "Заголовок"
    id_ID: "Judul"
  - key: "Text"
    en_US: "Text"
    ja_JP: "テキスト"
    zh_CN: "文本"
    ko_KR: "텍스트"
    es_ES: "Texto"
    fr_FR: "Texte"
    de_DE: "Text"
    pt_PT: "Texto"
    ru_RU: "Текст"
    id_ID: "Teks"
  - key: "Comment"
    en_US: "Comment"
    ja_JP: "コメント"
    zh_CN: "评论"
    ko_KR: "논평"
    es_ES: "Comentario"
    fr_FR: "Commentaire"
    de_DE: "Kommentar"
    pt_PT: "Comentário"
    ru_RU: "Комментарий"
    id_ID: "Komentar"
  - key: "Link"
    en_US: "Link"
    ja_JP: "リンク"
    zh_CN: "链接"
    ko_KR: "링크"
    es_ES: "Enlace"
    fr_FR: "Lien"
    de_DE: "Link"
    pt_PT: "Link"
    ru_RU: "Ссылка"
    id_ID: "Tautan"
  - key: "Icon"
    en_US: "Icon"
    ja_JP: "アイコン"
    zh_CN: "图标"
    ko_KR: "상"
    es_ES: "Icono"
    fr_FR: "Icône"
    de_DE: "Symbol"
    pt_PT: "Ícone"
    ru_RU: "Иконка"
    id_ID: "Ikon"
  - key: "Share"
    en_US: "Share"
    ja_JP: "シェア"
    zh_CN: "分享"
    ko_KR: "공유하다"
    es_ES: "Compartir"
    fr_FR: "Partager"
    de_DE: "Teilen"
    pt_PT: "Compartilhar"
    ru_RU: "Поделиться"
    id_ID: "Bagikan"
  - key: "Tag"
    en_US: "Tag"
    ja_JP: "タグ"
    zh_CN: "标签"
    ko_KR: "꼬리표"
    es_ES: "Etiqueta"
    fr_FR: "Étiquette"
    de_DE: "Tag"
    pt_PT: "Tag"
    ru_RU: "Тег"
    id_ID: "Tag"
  - key: "Tags"
    en_US: "Tags"
    ja_JP: "タグ"
    zh_CN: "标签"
    ko_KR: "꼬리표"
    es_ES: "Etiquetas"
    fr_FR: "Étiquettes"
    de_DE: "Tags"
    pt_PT: "Tags"
    ru_RU: "Теги"
    id_ID: "Tag"
  - key: "Events"
    en_US: "Events"
    ja_JP: "イベント"
    zh_CN: "事件"
    ko_KR: "행사"
    es_ES: "Eventos"
    fr_FR: "Événements"
    de_DE: "Veranstaltungen"
    pt_PT: "Eventos"
    ru_RU: "События"
    id_ID: "Acara"
  - key: "Category"
    en_US: "Category"
    ja_JP: "カテゴリー"
    zh_CN: "类别"
    ko_KR: "범주"
    es_ES: "Categoría"
    fr_FR: "Catégorie"
    de_DE: "Kategorie"
    pt_PT: "Categoria"
    ru_RU: "Категория"
    id_ID: "Kategori"
  - key: "Block"
    en_US: "Block"
    ja_JP: "ブロック"
    zh_CN: "堵塞"
    ko_KR: "차단하다"
    es_ES: "Bloquear"
    fr_FR: "Bloquer"
    de_DE: "Blockieren"
    pt_PT: "Bloquear"
    ru_RU: "Заблокировать"
    id_ID: "Blokir"
  - key: "Talk"
    en_US: "Talk"
    ja_JP: "トーク"
    zh_CN: "讲话"
    ko_KR: "말하다"
    es_ES: "Hablar"
    fr_FR: "Parler"
    de_DE: "Sprechen"
    pt_PT: "Falar"
    ru_RU: "Разговор"
    id_ID: "Bicara"
  - key: "Scenario"
    en_US: "Scenario"
    ja_JP: "シナリオ"
    zh_CN: "设想"
    ko_KR: "대본"
    es_ES: "Escenario"
    fr_FR: "Scénario"
    de_DE: "Szenario"
    pt_PT: "Cenário"
    ru_RU: "Сценарий"
    id_ID: "Skenario"
  - key: "Random"
    en_US: "Random"
    ja_JP: "ランダム"
    zh_CN: "随机的"
    ko_KR: "무작위의"
    es_ES: "Aleatorio"
    fr_FR: "Aléatoire"
    de_DE: "Zufällig"
    pt_PT: "Aleatório"
    ru_RU: "Случайный"
    id_ID: "Acak"
  - key: "Unchangeable"
    en_US: "Unchangeable"
    ja_JP: "変更不可"
    zh_CN: "它不能更改"
    ko_KR: "변경할 수 없습니다"
    es_ES: "Inmutable"
    fr_FR: "Inchangeable"
    de_DE: "Unveränderlich"
    pt_PT: "Imutável"
    ru_RU: "Неизменяемый"
    id_ID: "Tidak dapat diubah"
  - key: "See more"
    en_US: "See more"
    ja_JP: "もっと見る"
    zh_CN: "查看更多"
    ko_KR: "더보기"
    es_ES: "Ver más"
    fr_FR: "Voir plus"
    de_DE: "Mehr sehen"
    pt_PT: "Ver mais"
    ru_RU: "Показать больше"
    id_ID: "Lihat lebih"
  - key: "Latest"
    en_US: "Latest"
    ja_JP: "最新"
    zh_CN: "最新的"
    ko_KR: "최신"
    es_ES: "Último"
    fr_FR: "Dernier"
    de_DE: "Neueste"
    pt_PT: "Mais recente"
    ru_RU: "Последний"
    id_ID: "Terbaru"
  - key: "SNS"
    en_US: "SNS"
    ja_JP: "SNS"
    zh_CN: "SNS"
    ko_KR: "SNS"
    es_ES: "SNS"
    fr_FR: "SNS"
    de_DE: "SNS"
    pt_PT: "SNS"
    ru_RU: "SNS"
    id_ID: "SNS"
  - key: "Store"
    en_US: "Store"
    ja_JP: "ストア"
    zh_CN: "店铺"
    ko_KR: "스토어"
    es_ES: "Tienda"
    fr_FR: "Magasin"
    de_DE: "Geschäft"
    pt_PT: "Loja"
    ru_RU: "Магазин"
    id_ID: "Toko"
  - key: "Subscription"
    en_US: "Subscription"
    ja_JP: "サブスクリプション"
    zh_CN: "订阅"
    ko_KR: "구독"
    es_ES: "Suscripción"
    fr_FR: "Abonnement"
    de_DE: "Abonnement"
    pt_PT: "Assinatura"
    ru_RU: "Подписка"
    id_ID: "Berlangganan"
  - key: "Billing status"
    en_US: "Billing status"
    ja_JP: "課金状態"
    zh_CN: "计费状态"
    ko_KR: "청구 상태"
    es_ES: "Estado de facturación"
    fr_FR: "État de facturation"
    de_DE: "Abrechnungsstatus"
    pt_PT: "Status de cobrança"
    ru_RU: "Статус выставления счетов"
    id_ID: "Status penagihan"
  # Menu
  - key: "Menu"
    en_US: "Menu"
    ja_JP: "メニュー"
    zh_CN: "菜单"
    ko_KR: "메뉴"
    es_ES: "Menú"
    fr_FR: "Menu"
    de_DE: "Menü"
    pt_PT: "Menu"
    ru_RU: "Меню"
    id_ID: "Menu"
  - key: "Home"
    en_US: "Home"
    ja_JP: "ホーム"
    zh_CN: "家"
    ko_KR: "집"
    es_ES: "Inicio"
    fr_FR: "Accueil"
    de_DE: "Startseite"
    pt_PT: "Início"
    ru_RU: "Главная"
    id_ID: "Beranda"
  - key: "Contact"
    en_US: "Contact"
    ja_JP: "お問い合わせ"
    zh_CN: "询问"
    ko_KR: "문의"
    es_ES: "Contacto"
    fr_FR: "Contact"
    de_DE: "Kontakt"
    pt_PT: "Contato"
    ru_RU: "Контакт"
    id_ID: "Kontak"
  - key: "Calendar"
    en_US: "Calendar"
    ja_JP: "カレンダー"
    zh_CN: "日历"
    ko_KR: "달력"
    es_ES: "Calendario"
    fr_FR: "Calendrier"
    de_DE: "Kalender"
    pt_PT: "Calendário"
    ru_RU: "Календарь"
    id_ID: "Kalender"
  - key: "Profile"
    en_US: "Profile"
    ja_JP: "プロフィール"
    zh_CN: "轮廓"
    ko_KR: "프로필"
    es_ES: "Perfil"
    fr_FR: "Profil"
    de_DE: "Profil"
    pt_PT: "Perfil"
    ru_RU: "Профиль"
    id_ID: "Profil"
  - key: "Mypage"
    en_US: "Mypage"
    ja_JP: "マイページ"
    zh_CN: "我的页面"
    ko_KR: "나의 페이지"
    es_ES: "Mi página"
    fr_FR: "Ma page"
    de_DE: "Meine Seite"
    pt_PT: "Minha página"
    ru_RU: "Моя страница"
    id_ID: "Halaman saya"
  # Form
  - key: "Account"
    en_US: "Account"
    ja_JP: "アカウント"
    zh_CN: "帐户"
    ko_KR: "계정"
    es_ES: "Cuenta"
    fr_FR: "Compte"
    de_DE: "Konto"
    pt_PT: "Conta"
    ru_RU: "Аккаунт"
    id_ID: "Akun"
  - key: "User Information"
    en_US: "User Information"
    ja_JP: "ユーザー情報"
    zh_CN: "用户信息"
    ko_KR: "사용자 정보"
    es_ES: "Información del usuario"
    fr_FR: "Informations utilisateur"
    de_DE: "Benutzerinformationen"
    pt_PT: "Informações do usuário"
    ru_RU: "Информация о пользователе"
    id_ID: "Informasi pengguna"
  - key: "Login"
    en_US: "Login"
    ja_JP: "ログイン"
    zh_CN: "登录"
    ko_KR: "로그인"
    es_ES: "Iniciar sesión"
    fr_FR: "Connexion"
    de_DE: "Anmelden"
    pt_PT: "Entrar"
    ru_RU: "Войти"
    id_ID: "Masuk"
  - key: "Logout"
    en_US: "Logout"
    ja_JP: "ログアウト"
    zh_CN: "登出"
    ko_KR: "로그 아웃"
    es_ES: "Cerrar sesión"
    fr_FR: "Déconnexion"
    de_DE: "Abmelden"
    pt_PT: "Sair"
    ru_RU: "Выйти"
    id_ID: "Keluar"
  - key: "ID"
    en_US: "ID"
    ja_JP: "ID"
    zh_CN: "ID"
    ko_KR: "ID"
    es_ES: "ID"
    fr_FR: "ID"
    de_DE: "ID"
    pt_PT: "ID"
    ru_RU: "ID"
    id_ID: "ID"
  - key: "Name"
    en_US: "Name"
    ja_JP: "名前"
    zh_CN: "姓名"
    ko_KR: "이름"
    es_ES: "Nombre"
    fr_FR: "Nom"
    de_DE: "Name"
    pt_PT: "Nome"
    ru_RU: "Имя"
    id_ID: "Nama"
  - key: "Nickname"
    en_US: "Nickname"
    ja_JP: "ニックネーム"
    zh_CN: "昵称"
    ko_KR: "별명"
    es_ES: "Apodo"
    fr_FR: "Surnom"
    de_DE: "Spitzname"
    pt_PT: "Apelido"
    ru_RU: "Псевдоним"
    id_ID: "Nama panggilan"
  - key: "Family name"
    en_US: "Family name"
    ja_JP: "姓"
    zh_CN: "姓"
    ko_KR: "성"
    es_ES: "Apellido"
    fr_FR: "Nom de famille"
    de_DE: "Nachname"
    pt_PT: "Sobrenome"
    ru_RU: "Фамилия"
    id_ID: "Nama keluarga"
  - key: "Given name"
    en_US: "Given name"
    ja_JP: "名"
    zh_CN: "名"
    ko_KR: "명"
    es_ES: "Nombre"
    fr_FR: "Prénom"
    de_DE: "Vorname"
    pt_PT: "Nome"
    ru_RU: "Имя"
    id_ID: "Nama depan"
  - key: "Guest"
    en_US: "Guest"
    ja_JP: "ゲスト"
    zh_CN: "客人"
    ko_KR: "손님들"
    es_ES: "Invitado"
    fr_FR: "Invité"
    de_DE: "Gast"
    pt_PT: "Convidado"
    ru_RU: "Гость"
    id_ID: "Tamu"
  - key: "Gender"
    en_US: "Gender"
    ja_JP: "性別"
    zh_CN: "性别"
    ko_KR: "섹스"
    es_ES: "Género"
    fr_FR: "Genre"
    de_DE: "Geschlecht"
    pt_PT: "Gênero"
    ru_RU: "Пол"
    id_ID: "Jenis kelamin"
  - key: "Male"
    en_US: "Male"
    ja_JP: "男性"
    zh_CN: "男性"
    ko_KR: "남성"
    es_ES: "Masculino"
    fr_FR: "Masculin"
    de_DE: "Männlich"
    pt_PT: "Masculino"
    ru_RU: "Мужской"
    id_ID: "Laki-laki"
  - key: "Female"
    en_US: "Female"
    ja_JP: "女性"
    zh_CN: "女士"
    ko_KR: "여성"
    es_ES: "Femenino"
    fr_FR: "Féminin"
    de_DE: "Weiblich"
    pt_PT: "Feminino"
    ru_RU: "Женский"
    id_ID: "Perempuan"
  - key: "Address"
    en_US: "Address"
    ja_JP: "住所"
    zh_CN: "地址"
    ko_KR: "주소"
    es_ES: "Dirección"
    fr_FR: "Adresse"
    de_DE: "Adresse"
    pt_PT: "Endereço"
    ru_RU: "Адрес"
    id_ID: "Alamat"
  - key: "Age"
    en_US: "Age"
    ja_JP: "年齢"
    zh_CN: "年龄"
    ko_KR: "나이"
    es_ES: "Edad"
    fr_FR: "Âge"
    de_DE: "Alter"
    pt_PT: "Idade"
    ru_RU: "Возраст"
    id_ID: "Usia"
  - key: "Birthday"
    en_US: "Birthday"
    ja_JP: "生年月日"
    zh_CN: "出生日期"
    ko_KR: "생일"
    es_ES: "Cumpleaños"
    fr_FR: "Anniversaire"
    de_DE: "Geburtstag"
    pt_PT: "Aniversário"
    ru_RU: "День рождения"
    id_ID: "Ulang tahun"
  - key: "Work"
    en_US: "Work"
    ja_JP: "職業"
    zh_CN: "职业"
    ko_KR: "직업"
    es_ES: "Trabajo"
    fr_FR: "Travail"
    de_DE: "Arbeit"
    pt_PT: "Trabalho"
    ru_RU: "Работа"
    id_ID: "Pekerjaan"
  - key: "Phone number"
    en_US: "Phone number"
    ja_JP: "電話番号"
    zh_CN: "电话号码"
    ko_KR: "전화 번호"
    es_ES: "Número de teléfono"
    fr_FR: "Numéro de téléphone"
    de_DE: "Telefonnummer"
    pt_PT: "Número de telefone"
    ru_RU: "Номер телефона"
    id_ID: "Nomor telepon"
  - key: "Email"
    en_US: "Email"
    ja_JP: "メールアドレス"
    zh_CN: "邮件地址"
    ko_KR: "메일 주소"
    es_ES: "Correo electrónico"
    fr_FR: "E-mail"
    de_DE: "E-Mail"
    pt_PT: "E-mail"
    ru_RU: "Электронная почта"
    id_ID: "Email"
  - key: "Password"
    en_US: "Password"
    ja_JP: "パスワード"
    zh_CN: "密码"
    ko_KR: "비밀번호"
    es_ES: "Contraseña"
    fr_FR: "Mot de passe"
    de_DE: "Passwort"
    pt_PT: "Senha"
    ru_RU: "Пароль"
    id_ID: "Kata sandi"
  - key: "Confirm password"
    en_US: "Confirm password"
    ja_JP: "パスワードの確認"
    zh_CN: "确认密码"
    ko_KR: "비밀번호 확인"
    es_ES: "Confirmar contraseña"
    fr_FR: "Confirmer le mot de passe"
    de_DE: "Passwort bestätigen"
    pt_PT: "Confirmar senha"
    ru_RU: "Подтвердить пароль"
    id_ID: "Konfirmasi kata sandi"
  - key: "Reset password"
    en_US: "Reset password"
    ja_JP: "パスワードリセット"
    zh_CN: "重设密码"
    ko_KR: "비밀번호 초기화"
    es_ES: "Restablecer contraseña"
    fr_FR: "Réinitialiser le mot de passe"
    de_DE: "Passwort zurücksetzen"
    pt_PT: "Redefinir senha"
    ru_RU: "Сброс пароля"
    id_ID: "Reset kata sandi"
  - key: "Forgot your password?"
    en_US: "Forgot your password?"
    ja_JP: "パスワードを忘れた方はこちら"
    zh_CN: "如果您忘记了密码，请单击此处"
    ko_KR: "비밀번호를 잊어 버린 경우 여기를 클릭하십시오"
    es_ES: "¿Olvidaste tu contraseña?"
    fr_FR: "Mot de passe oublié ?"
    de_DE: "Passwort vergessen?"
    pt_PT: "Esqueceu sua senha?"
    ru_RU: "Забыли пароль?"
    id_ID: "Lupa kata sandi?"
  - key: "Reauthentication"
    en_US: "Reauthentication"
    ja_JP: "再認証"
    zh_CN: "重新认证"
    ko_KR: "재 인증"
    es_ES: "Reautenticación"
    fr_FR: "Réauthentification"
    de_DE: "Erneute Authentifizierung"
    pt_PT: "Reautenticação"
    ru_RU: "Повторная аутентификация"
    id_ID: "Autentikasi ulang"
  - key: "Sign in with {provider}"
    en_US: "Sign in with {provider}"
    ja_JP: "{provider}でサインイン"
    zh_CN: "使用 {provider} 登录"
    ko_KR: "{provider} 로 로그인"
    es_ES: "Iniciar sesión con {provider}"
    fr_FR: "Se connecter avec {provider}"
    de_DE: "Mit {provider} anmelden"
    pt_PT: "Entrar com {provider}"
    ru_RU: "Войти через {provider}"
    id_ID: "Masuk dengan {provider}"
  - key: "Please re-enter your password to re-authenticate."
    en_US: "Please re-enter your password to re-authenticate."
    ja_JP: "パスワードを再度入力して再認証をしてください。"
    zh_CN: "再次输入密码并重新实现。"
    ko_KR: "비밀번호를 다시 입력하고 다시 인증하십시오."
    es_ES: "Por favor, vuelve a introducir tu contraseña para reautenticar."
    fr_FR: "Veuillez saisir à nouveau votre mot de passe pour vous réauthentifier."
    de_DE: "Bitte geben Sie Ihr Passwort erneut ein, um sich erneut zu authentifizieren."
    pt_PT: "Por favor, insira sua senha novamente para reautenticar."
    ru_RU: "Пожалуйста, введите пароль еще раз для повторной аутентификации."
    id_ID: "Silakan masukkan kembali kata sandi Anda untuk mengautentikasi ulang."
  - key: "Send email"
    en_US: "Send email"
    ja_JP: "メールを送信"
    zh_CN: "发送电子邮件"
    ko_KR: "이메일을 보내다"
    es_ES: "Enviar correo electrónico"
    fr_FR: "Envoyer un e-mail"
    de_DE: "E-Mail senden"
    pt_PT: "Enviar e-mail"
    ru_RU: "Отправить электронное письмо"
    id_ID: "Kirim email"
  - key: "Send code"
    en_US: "Send code"
    ja_JP: "コードを送信"
    zh_CN: "发送代码"
    ko_KR: "코드를 보내십시오"
    es_ES: "Enviar código"
    fr_FR: "Envoyer le code"
    de_DE: "Code senden"
    pt_PT: "Enviar código"
    ru_RU: "Отправить код"
    id_ID: "Kirim kode"
  - key: "Profile Settings"
    en_US: "Profile Settings"
    ja_JP: "プロフィール設定"
    zh_CN: "个人资料设置"
    ko_KR: "프로필 설정"
    es_ES: "Configuración del perfil"
    fr_FR: "Paramètres du profil"
    de_DE: "Profileinstellungen"
    pt_PT: "Configurações do perfil"
    ru_RU: "Настройки профиля"
    id_ID: "Pengaturan profil"
  - key: "Profile Check"
    en_US: "Profile Check"
    ja_JP: "プロフィール確認"
    zh_CN: "确认个人资料"
    ko_KR: "프로필 확인"
    es_ES: "Verificación del perfil"
    fr_FR: "Vérification du profil"
    de_DE: "Profilüberprüfung"
    pt_PT: "Verificação do perfil"
    ru_RU: "Проверка профиля"
    id_ID: "Pemeriksaan profil"
  - key: "Notification"
    en_US: "Notification"
    ja_JP: "通知"
    zh_CN: "通知"
    ko_KR: "알림"
    es_ES: "Notificación"
    fr_FR: "Notification"
    de_DE: "Benachrichtigung"
    pt_PT: "Notificação"
    ru_RU: "Уведомление"
    id_ID: "Pemberitahuan"
  - key: "Notification Settings"
    en_US: "Notification Settings"
    ja_JP: "通知設定"
    zh_CN: "通知设置"
    ko_KR: "알림 설정"
    es_ES: "Configuración de notificaciones"
    fr_FR: "Paramètres de notification"
    de_DE: "Benachrichtigungseinstellungen"
    pt_PT: "Configurações de notificação"
    ru_RU: "Настройки уведомлений"
    id_ID: "Pengaturan notifikasi"
  - key: "Account Deletion"
    en_US: "Account Deletion"
    ja_JP: "アカウント削除"
    zh_CN: "帐户删除"
    ko_KR: "계정 삭제"
    es_ES: "Eliminación de cuenta"
    fr_FR: "Suppression de compte"
    de_DE: "Kontolöschung"
    pt_PT: "Exclusão de conta"
    ru_RU: "Удаление аккаунта"
    id_ID: "Penghapusan akun"
  - key: "Add media by taking pictures with the camera"
    en_US: "Add media by taking pictures with the camera"
    ja_JP: "カメラで撮影してメディアを追加"
    zh_CN: "通过相机拍摄添加媒体"
    ko_KR: "카메라로 촬영하여 미디어 추가"
    es_ES: "Agregar medios tomando fotos con la cámara"
    fr_FR: "Ajouter des médias en prenant des photos avec l'appareil photo"
    de_DE: "Medien durch Aufnahme mit der Kamera hinzufügen"
    pt_PT: "Adicionar mídia tirando fotos com a câmera"
    ru_RU: "Добавить медиа, сделав фото камерой"
    id_ID: "Tambahkan media dengan mengambil gambar dengan kamera"
  - key: "Add media from the library"
    en_US: "Add media from the library"
    ja_JP: "ライブラリからメディアを追加"
    zh_CN: "从库中添加媒体"
    ko_KR: "라이브러리에서 미디어 추가"
    es_ES: "Agregar medios desde la biblioteca"
    fr_FR: "Ajouter des médias depuis la bibliothèque"
    de_DE: "Medien aus der Bibliothek hinzufügen"
    pt_PT: "Adicionar mídia da biblioteca"
    ru_RU: "Добавить медиа из библиотеки"
    id_ID: "Tambahkan media dari perpustakaan"
  - key: "Enter the 6-digit code from the SMS."
    en_US: "Enter the 6-digit code from the SMS."
    ja_JP: "SMSに記載されている6桁のコードを入力してください。"
    zh_CN: "输入SMS中列出的6个数字代码。"
    ko_KR: "SMS에 나열된 6 자리 코드를 입력하십시오."
    es_ES: "Ingrese el código de 6 dígitos del SMS."
    fr_FR: "Entrez le code à 6 chiffres du SMS."
    de_DE: "Geben Sie den 6-stelligen Code aus der SMS ein."
    pt_PT: "Digite o código de 6 dígitos do SMS."
    ru_RU: "Введите 6-значный код из SMS."
    id_ID: "Masukkan kode 6 digit dari SMS."
  - key: "You will log out. Are you OK?"
    en_US: "You will log out.\\n\\nAre you OK?"
    ja_JP: "ログアウトします。\\n\\nよろしいですか？"
    zh_CN: "登出。\\n\\n您确定吗？"
    ko_KR: "로그 아웃. \\n\\n확실합니까?"
    es_ES: "Cerrarás sesión.\\n\\n¿Estás seguro?"
    fr_FR: "Vous allez vous déconnecter.\\n\\nÊtes-vous sûr ?"
    de_DE: "Sie werden abgemeldet.\\n\\nSind Sie sicher?"
    pt_PT: "Você sairá.\\n\\nTem certeza?"
    ru_RU: "Вы выйдете из системы.\\n\\nВы уверены?"
    id_ID: "Anda akan keluar.\\n\\nApakah Anda yakin?"
  - key: "Password reset email has been sent to you. Please use the link in the email to set a new password."
    en_US: "Password reset email has been sent to you.\\n\\nPlease use the link in the email to set a new password."
    ja_JP: "パスワードリセットメールを送信しました。\\n\\nメール中に記載されているリンクから新しいパスワードを設定してください。"
    zh_CN: "我发送了密码重置电子邮件。\\n\\n从电子邮件中列出的链接中设置一个新密码。"
    ko_KR: "비밀번호 재설정 이메일을 보냈습니다. \\n\\n이메일에 나열된 링크에서 새 비밀번호를 설정합니다."
    es_ES: "Se le ha enviado un correo electrónico para restablecer la contraseña.\\n\\nUtilice el enlace del correo electrónico para establecer una nueva contraseña."
    fr_FR: "Un e-mail de réinitialisation du mot de passe vous a été envoyé.\\n\\nVeuillez utiliser le lien dans l'e-mail pour définir un nouveau mot de passe."
    de_DE: "Eine E-Mail zum Zurücksetzen des Passworts wurde an Sie gesendet.\\n\\nBitte verwenden Sie den Link in der E-Mail, um ein neues Passwort festzulegen."
    pt_PT: "Um e-mail de redefinição de senha foi enviado para você.\\n\\nUse o link no e-mail para definir uma nova senha."
    ru_RU: "Вам отправлено письмо для сброса пароля.\\n\\nПожалуйста, используйте ссылку в письме, чтобы установить новый пароль."
    id_ID: "Email reset kata sandi telah dikirim kepada Anda.\\n\\nSilakan gunakan tautan di email untuk mengatur kata sandi baru."
  - key: "Please register again."
    en_US: "Please register again."
    ja_JP: "お手数ですが、再度新規登録をお願いします。"
    zh_CN: "对于给您带来的不便，我们深表歉意，但请重新注册。"
    ko_KR: "죄송 합니다만, 다시 신규 등록을 부탁드립니다."
    es_ES: "Por favor, regístrese de nuevo."
    fr_FR: "Veuillez vous inscrire à nouveau."
    de_DE: "Bitte registrieren Sie sich erneut."
    pt_PT: "Por favor, registre-se novamente."
    ru_RU: "Пожалуйста, зарегистрируйтесь снова."
    id_ID: "Silakan daftar lagi."
  - key: "Please try again."
    en_US: "Please try again."
    ja_JP: "もう一度お試しください。"
    zh_CN: "请再试一次。"
    ko_KR: "다시 시도하십시오."
    es_ES: "Por favor, inténtelo de nuevo."
    fr_FR: "Veuillez réessayer."
    de_DE: "Bitte versuchen Sie es erneut."
    pt_PT: "Por favor, tente novamente."
    ru_RU: "Пожалуйста, попробуйте еще раз."
    id_ID: "Silakan coba lagi."
  - key: "Do you want to delete your account? Once an account is deleted, it cannot be restored."
    en_US: "Do you want to delete your account?\\n\\nOnce an account is deleted, it cannot be restored."
    ja_JP: "アカウントを削除しますか？\\n\\n一度削除すると元に戻すことはできません。"
    zh_CN: "您想删除您的帐户吗？ \\n\\n一旦删除，将无法恢复。"
    ko_KR: "계정을 삭제하시겠습니까? \\n\\n한 번 삭제하면 되돌릴 수 없습니다."
    es_ES: "¿Quieres eliminar tu cuenta?\\n\\nUna vez que se elimina una cuenta, no se puede restaurar."
    fr_FR: "Voulez-vous supprimer votre compte ?\\n\\nUne fois qu'un compte est supprimé, il ne peut pas être restauré."
    de_DE: "Möchten Sie Ihr Konto löschen?\\n\\nSobald ein Konto gelöscht wurde, kann es nicht wiederhergestellt werden."
    pt_PT: "Você deseja excluir sua conta?\\n\\nUma vez que uma conta é excluída, ela não pode ser restaurada."
    ru_RU: "Вы хотите удалить свой аккаунт?\\n\\nПосле удаления аккаунта его невозможно восстановить."
    id_ID: "Apakah Anda ingin menghapus akun Anda?\\n\\nSetelah akun dihapus, akun tersebut tidak dapat dipulihkan."
  - key: "Since your subscription is active, you cannot delete your account. Please cancel your subscription and try again."
    en_US: "Since your subscription is active, you cannot delete your account.\\n\\nPlease cancel your subscription and try again."
    ja_JP: "サブスクリプションが有効のため、アカウント削除はできません。\\n\\n一度サブスクリプションを解約した後、再度お試しください。"
    zh_CN: "您的帐户无法删除，因为您的订阅处于活动状态。 \\n\\n请取消您的订阅并重试。"
    ko_KR: "구독이 활성화되어 계정을 삭제할 수 없습니다."
    es_ES: "Dado que su suscripción está activa, no puede eliminar su cuenta.\\n\\nCancele su suscripción e inténtelo de nuevo."
    fr_FR: "Étant donné que votre abonnement est actif, vous ne pouvez pas supprimer votre compte.\\n\\nVeuillez annuler votre abonnement et réessayer."
    de_DE: "Da Ihr Abonnement aktiv ist, können Sie Ihr Konto nicht löschen.\\n\\nBitte kündigen Sie Ihr Abonnement und versuchen Sie es erneut."
    pt_PT: "Como sua assinatura está ativa, você não pode excluir sua conta.\\n\\nCancele sua assinatura e tente novamente."
    ru_RU: "Поскольку ваша подписка активна, вы не можете удалить свой аккаунт.\\n\\nПожалуйста, отмените подписку и попробуйте еще раз."
    id_ID: "Karena langganan Anda aktif, Anda tidak dapat menghapus akun Anda.\\n\\nSilakan batalkan langganan Anda dan coba lagi."
  - key: "Could not login. Please check your login information again."
    en_US: "Could not login. Please check your login information again."
    ja_JP: "ログインできませんでした。ログイン情報を再度ご確認ください。"
    zh_CN: "我无法登录。请再次检查登录信息。"
    ko_KR: "로그인 할 수 없었습니다. 로그인 정보를 다시 확인하십시오."
    es_ES: "No se pudo iniciar sesión. Por favor, verifique su información de inicio de sesión nuevamente."
    fr_FR: "Impossible de se connecter. Veuillez vérifier à nouveau vos informations de connexion."
    de_DE: "Anmeldung fehlgeschlagen. Bitte überprüfen Sie Ihre Anmeldedaten erneut."
    pt_PT: "Não foi possível fazer login. Por favor, verifique suas informações de login novamente."
    ru_RU: "Не удалось войти в систему. Пожалуйста, проверьте данные для входа еще раз."
    id_ID: "Tidak dapat masuk. Silakan periksa informasi login Anda lagi."
  - key: "Initialization failed. Exit the application. {error} {stacktrace}"
    en_US: "Initialization failed. Exit the application. \\n\\n{error}\\n{stacktrace}"
    ja_JP: "初期化に失敗しました。アプリを終了します。\\n\\n{error}\\n{stacktrace}"
    zh_CN: "初始化失败。结束应用程序。\\n\\n{error}\\n{stacktrace}"
    ko_KR: "초기화 실패. 앱을 끝내십시오.\\n\\n{error}\\n{stacktrace}"
    es_ES: "La inicialización falló. Salir de la aplicación.\\n\\n{error}\\n{stacktrace}"
    fr_FR: "L'initialisation a échoué. Quitter l'application.\\n\\n{error}\\n{stacktrace}"
    de_DE: "Initialisierung fehlgeschlagen. Anwendung beenden.\\n\\n{error}\\n{stacktrace}"
    pt_PT: "A inicialização falhou. Sair do aplicativo.\\n\\n{error}\\n{stacktrace}"
    ru_RU: "Инициализация не удалась. Выйти из приложения.\\n\\n{error}\\n{stacktrace}"
    id_ID: "Inisialisasi gagal. Keluar dari aplikasi.\\n\\n{error}\\n{stacktrace}"
  - key: "There is a new update"
    en_US: "There is a new update"
    ja_JP: "新しいアップデート"
    zh_CN: "新更新"
    ko_KR: "새로운 업데이트"
    es_ES: "Hay una nueva actualización"
    fr_FR: "Il y a une nouvelle mise à jour"
    de_DE: "Es gibt ein neues Update"
    pt_PT: "Há uma nova atualização"
    ru_RU: "Доступно новое обновление"
    id_ID: "Ada pembaruan baru"
  - key: "There is a new update. Please update the application in the store and then launch the application again."
    en_US: "There is a new update.\\n\\nPlease update the application in the store and then launch the application again."
    ja_JP: "新しいアップデートがあります。\\n\\nストアでアプリをアップデートしてから再度アプリを起動してください。"
    zh_CN: "有新的更新。\\n\\n请从商店更新应用程序，然后再次启动该应用程序。"
    ko_KR: "새로운 업데이트가 있습니다.\\n\\n스토어에서 앱을 업데이트한 다음 앱을 다시 시작하세요."
    es_ES: "Hay una nueva actualización.\\n\\nActualice la aplicación en la tienda y luego vuelva a iniciar la aplicación."
    fr_FR: "Il y a une nouvelle mise à jour.\\n\\nVeuillez mettre à jour l'application dans le magasin, puis relancer l'application."
    de_DE: "Es gibt ein neues Update.\\n\\nBitte aktualisieren Sie die Anwendung im Store und starten Sie die Anwendung dann erneut."
    pt_PT: "Há uma nova atualização.\\n\\nAtualize o aplicativo na loja e, em seguida, inicie o aplicativo novamente."
    ru_RU: "Доступно новое обновление.\\n\\nПожалуйста, обновите приложение в магазине и затем запустите приложение снова."
    id_ID: "Ada pembaruan baru.\\n\\nSilakan perbarui aplikasi di toko dan kemudian luncurkan aplikasi lagi."
  # Sentence
  - key: "{do} {name}"
    en_US: "{do} {name}"
    ja_JP: "{name}{do}"
    zh_CN: "{do}{name}"
    ko_KR: "{name} {do}"
    es_ES: "{do} {name}"
    fr_FR: "{do} {name}"
    de_DE: "{do} {name}"
    pt_PT: "{do} {name}"
    ru_RU: "{do} {name}"
    id_ID: "{do} {name}"
  - key: "{obj1} on {obj2}"
    en_US: "{obj1} on {obj2}"
    ja_JP: "{obj2}上の{obj1}"
    zh_CN: "{obj1}在{obj2}上"
    ko_KR: "{obj2}의{obj1}"
    es_ES: "{obj1} en {obj2}"
    fr_FR: "{obj1} sur {obj2}"
    de_DE: "{obj1} auf {obj2}"
    pt_PT: "{obj1} em {obj2}"
    ru_RU: "{obj1} на {obj2}"
    id_ID: "{obj1} di {obj2}"
  - key: "{obj1} in {obj2}"
    en_US: "{obj1} in {obj2}"
    ja_JP: "{obj2}中の{obj1}"
    zh_CN: "{obj2}在{obj1}中"
    ko_KR: "{obj2}의{obj1}"
    es_ES: "{obj1} en {obj2}"
    fr_FR: "{obj1} dans {obj2}"
    de_DE: "{obj1} in {obj2}"
    pt_PT: "{obj1} em {obj2}"
    ru_RU: "{obj1} в {obj2}"
    id_ID: "{obj1} di dalam {obj2}"
  - key: "{obj1} of {obj2}"
    en_US: "{obj1} of {obj2}"
    ja_JP: "{obj2}の{obj1}"
    zh_CN: "{obj2}的{obj1}"
    ko_KR: "{obj2}의{obj1}"
    es_ES: "{obj1} de {obj2}"
    fr_FR: "{obj1} de {obj2}"
    de_DE: "{obj1} von {obj2}"
    pt_PT: "{obj1} de {obj2}"
    ru_RU: "{obj1} из {obj2}"
    id_ID: "{obj1} dari {obj2}"
  - key: "{obj1} and {obj2}"
    en_US: "{obj1} and {obj2}"
    ja_JP: "{obj2}と{obj1}"
    zh_CN: "{obj2}和{obj1}"
    ko_KR: "{obj2}및{obj1}"
    es_ES: "{obj1} y {obj2}"
    fr_FR: "{obj1} et {obj2}"
    de_DE: "{obj1} und {obj2}"
    pt_PT: "{obj1} e {obj2}"
    ru_RU: "{obj1} и {obj2}"
    id_ID: "{obj1} dan {obj2}"
  - key: "{obj1} or {obj2}"
    en_US: "{obj1} or {obj2}"
    ja_JP: "{obj2}または{obj1}"
    zh_CN: "{obj2}或{obj1}"
    ko_KR: "{obj2}또는{obj1}"
    es_ES: "{obj1} o {obj2}"
    fr_FR: "{obj1} ou {obj2}"
    de_DE: "{obj1} oder {obj2}"
    pt_PT: "{obj1} ou {obj2}"
    ru_RU: "{obj1} или {obj2}"
    id_ID: "{obj1} atau {obj2}"
  - key: "{name} has been completed."
    en_US: "{name} has been completed."
    ja_JP: "{name}が完了しました。"
    zh_CN: "{name}已完成。"
    ko_KR: "{name}이 완료되었습니다."
    es_ES: "{name} se ha completado."
    fr_FR: "{name} a été complété."
    de_DE: "{name} wurde abgeschlossen."
    pt_PT: "{name} foi concluído."
    ru_RU: "{name} завершено."
    id_ID: "{name} telah selesai."
  - key: "{name} have been completed."
    en_US: "{name} have been completed."
    ja_JP: "{name}が完了しました。"
    zh_CN: "{name}已完成。"
    ko_KR: "{name}이 완료되었습니다."
    es_ES: "{name} se han completado."
    fr_FR: "{name} ont été complétés."
    de_DE: "{name} wurden abgeschlossen."
    pt_PT: "{name} foram concluídos."
    ru_RU: "{name} завершены."
    id_ID: "{name} telah selesai."
  - key: "{name} has been successful."
    en_US: "{name} has been successful."
    ja_JP: "{name}に成功しました。"
    zh_CN: "我成功地{name}。"
    ko_KR: "{name}에서 성공했습니다."
    es_ES: "{name} ha sido exitoso."
    fr_FR: "{name} a réussi."
    de_DE: "{name} war erfolgreich."
    pt_PT: "{name} foi bem-sucedido."
    ru_RU: "{name} выполнено успешно."
    id_ID: "{name} telah berhasil."
  - key: "{name} have been successful."
    en_US: "{name} have been successful."
    ja_JP: "{name}に成功しました。"
    zh_CN: "我成功地{name}。"
    ko_KR: "{name}에서 성공했습니다."
    es_ES: "{name} han sido exitosos."
    fr_FR: "{name} ont réussi."
    de_DE: "{name} waren erfolgreich."
    pt_PT: "{name} foram bem-sucedidos."
    ru_RU: "{name} выполнены успешно."
    id_ID: "{name} telah berhasil."
  - key: "{name} has failed."
    en_US: "{name} has failed."
    ja_JP: "{name}に失敗しました。"
    zh_CN: "{name}失败。"
    ko_KR: "{name}가 실패했습니다."
    es_ES: "{name} ha fallado."
    fr_FR: "{name} a échoué."
    de_DE: "{name} ist fehlgeschlagen."
    pt_PT: "{name} falhou."
    ru_RU: "{name} не удалось."
    id_ID: "{name} telah gagal."
  - key: "{name} have failed."
    en_US: "{name} have failed."
    ja_JP: "{name}に失敗しました。"
    zh_CN: "{name}失败。"
    ko_KR: "{name}가 실패했습니다."
    es_ES: "{name} han fallado."
    fr_FR: "{name} ont échoué."
    de_DE: "{name} sind fehlgeschlagen."
    pt_PT: "{name} falharam."
    ru_RU: "{name} не удались."
    id_ID: "{name} telah gagal."
  - key: "{name} has occured."
    en_US: "{name} has occured."
    ja_JP: "{name}が発生しました。"
    zh_CN: "{name}发生。"
    ko_KR: "{name}가 발생했습니다."
    es_ES: "{name} ha ocurrido."
    fr_FR: "{name} a eu lieu."
    de_DE: "{name} ist aufgetreten."
    pt_PT: "{name} ocorreu."
    ru_RU: "{name} произошло."
    id_ID: "{name} terjadi."
  - key: "Please enter {name}."
    en_US: "Please enter {name}."
    ja_JP: "{name}を入力してください。"
    zh_CN: "输入{name}。"
    ko_KR: "{name}을 입력하세요."
    es_ES: "Por favor ingrese {name}."
    fr_FR: "Veuillez entrer {name}."
    de_DE: "Bitte geben Sie {name} ein."
    pt_PT: "Por favor, insira {name}."
    ru_RU: "Пожалуйста, введите {name}."
    id_ID: "Silakan masukkan {name}."
  - key: "Please select {name}."
    en_US: "Please select {name}."
    ja_JP: "{name}を選択してください。"
    zh_CN: "请选择{name}。"
    ko_KR: "{name}을 선택하세요."
    es_ES: "Por favor seleccione {name}."
    fr_FR: "Veuillez sélectionner {name}."
    de_DE: "Bitte wählen Sie {name}."
    pt_PT: "Por favor, selecione {name}."
    ru_RU: "Пожалуйста, выберите {name}."
    id_ID: "Silakan pilih {name}."
  - key: "{name} is not entered."
    en_US: "{name} is not entered."
    ja_JP: "{name}が入力されていません。"
    zh_CN: "{name}未输入。"
    ko_KR: "{name}이 입력되지 않았습니다."
    es_ES: "{name} no se ha ingresado."
    fr_FR: "{name} n'est pas entré."
    de_DE: "{name} wurde nicht eingegeben."
    pt_PT: "{name} não foi inserido."
    ru_RU: "{name} не введено."
    id_ID: "{name} tidak dimasukkan."
  - key: "{name} is not selected."
    en_US: "{name} is not selected."
    ja_JP: "{name}が選択されていません。"
    zh_CN: "{name}未选择。"
    ko_KR: "{name}이 선택되지 않았습니다."
    es_ES: "{name} no está seleccionado."
    fr_FR: "{name} n'est pas sélectionné."
    de_DE: "{name} ist nicht ausgewählt."
    pt_PT: "{name} não está selecionado."
    ru_RU: "{name} не выбрано."
    id_ID: "{name} tidak dipilih."
  - key: "{name} may be incorrect."
    en_US: "{name} may be incorrect."
    ja_JP: "{name}が間違っている可能性があります。"
    zh_CN: "{name}可能是错误的。"
    ko_KR: "{name}이 잘못 될 수 있습니다."
    es_ES: "{name} puede ser incorrecto."
    fr_FR: "{name} peut être incorrect."
    de_DE: "{name} könnte falsch sein."
    pt_PT: "{name} pode estar incorreto."
    ru_RU: "{name} может быть неверным."
    id_ID: "{name} mungkin salah."
  - key: "{name} does not match."
    en_US: "{name} does not match."
    ja_JP: "{name}が一致しません。"
    zh_CN: "{name}不匹配。"
    ko_KR: "{name}이 일치하지 않습니다."
    es_ES: "{name} no coincide."
    fr_FR: "{name} ne correspond pas."
    de_DE: "{name} stimmt nicht überein."
    pt_PT: "{name} não corresponde."
    ru_RU: "{name} не совпадает."
    id_ID: "{name} tidak cocok."
  - key: "{name} not found."
    en_US: "{name} not found."
    ja_JP: "{name}が見つかりません。"
    zh_CN: "{name}找不到。"
    ko_KR: "{name}을 찾을 수 없습니다."
    es_ES: "{name} no encontrado."
    fr_FR: "{name} introuvable."
    de_DE: "{name} nicht gefunden."
    pt_PT: "{name} não encontrado."
    ru_RU: "{name} не найдено."
    id_ID: "{name} tidak ditemukan."
  - key: "{name} has started."
    en_US: "{name} has started."
    ja_JP: "{name}を開始しました。"
    zh_CN: "{name} 开始了。"
    ko_KR: "{name}을 시작했습니다."
    es_ES: "{name} ha comenzado."
    fr_FR: "{name} a commencé."
    de_DE: "{name} hat begonnen."
    pt_PT: "{name} começou."
    ru_RU: "{name} начато."
    id_ID: "{name} telah dimulai."
  - key: "{name} have started."
    en_US: "{name} have started."
    ja_JP: "{name}を開始しました。"
    zh_CN: "{name} 开始了。"
    ko_KR: "{name}을 시작했습니다."
    es_ES: "{name} han comenzado."
    fr_FR: "{name} ont commencé."
    de_DE: "{name} haben begonnen."
    pt_PT: "{name} começaram."
    ru_RU: "{name} начаты."
    id_ID: "{name} telah dimulai."
  - key: "{name} has finished."
    en_US: "{name} has finished."
    ja_JP: "{name}を終了しました。"
    zh_CN: "{name} 已完成。"
    ko_KR: "{name}을 종료했습니다."
    es_ES: "{name} ha terminado."
    fr_FR: "{name} est terminé."
    de_DE: "{name} ist beendet."
    pt_PT: "{name} terminou."
    ru_RU: "{name} завершено."
    id_ID: "{name} telah selesai."
  - key: "{name} have finished."
    en_US: "{name} have finished."
    ja_JP: "{name}を終了しました。"
    zh_CN: "{name} 已完成。"
    ko_KR: "{name}을 종료했습니다."
    es_ES: "{name} han terminado."
    fr_FR: "{name} sont terminés."
    de_DE: "{name} sind beendet."
    pt_PT: "{name} terminaram."
    ru_RU: "{name} завершены."
    id_ID: "{name} telah selesai."
  - key: "{name} has been restored."
    en_US: "{name} has been restored."
    ja_JP: "{name}を復元しました。"
    zh_CN: "{name} 已恢复。"
    ko_KR: "{name}을 복원했습니다."
    es_ES: "{name} ha sido restaurado."
    fr_FR: "{name} a été restauré."
    de_DE: "{name} wurde wiederhergestellt."
    pt_PT: "{name} foi restaurado."
    ru_RU: "{name} восстановлено."
    id_ID: "{name} telah dipulihkan."
  - key: "{name} have been restored."
    en_US: "{name} have been restored."
    ja_JP: "{name}を復元しました。"
    zh_CN: "{name} 已恢复。"
    ko_KR: "{name}을 복원했습니다."
    es_ES: "{name} han sido restaurados."
    fr_FR: "{name} ont été restaurés."
    de_DE: "{name} wurden wiederhergestellt."
    pt_PT: "{name} foram restaurados."
    ru_RU: "{name} восстановлены."
    id_ID: "{name} telah dipulihkan."
  - key: "You will delete {name}. Once deleted, it cannot be undone."
    en_US: "You will delete {name}.\\n\\nOnce deleted, it cannot be undone."
    ja_JP: "{name}を削除します。\\n\\n一度削除すると元に戻すことができません。"
    zh_CN: "删除{name}。\\n\\n一旦删除，它就无法恢复。"
    ko_KR: "{name}을 삭제합니다. \\n\\n일단 삭제되면 복원 할 수 없습니다."
    es_ES: "Eliminará {name}.\\n\\nUna vez eliminado, no se puede deshacer."
    fr_FR: "Vous allez supprimer {name}.\\n\\nUne fois supprimé, cela ne peut pas être annulé."
    de_DE: "Sie werden {name} löschen.\\n\\nEinmal gelöscht, kann es nicht rückgängig gemacht werden."
    pt_PT: "Você excluirá {name}.\\n\\nUma vez excluído, não pode ser desfeito."
    ru_RU: "Вы удалите {name}.\\n\\nПосле удаления это действие нельзя отменить."
    id_ID: "Anda akan menghapus {name}.\\n\\nSetelah dihapus, tidak dapat dibatalkan."
  - key: "{name} is already deleted."
    en_US: "{name} is already deleted."
    ja_JP: "{name}はすでに削除されています。"
    zh_CN: "{name}已被删除。"
    ko_KR: "{name}는 이미 삭제되었습니다."
    es_ES: "{name} ya está eliminado."
    fr_FR: "{name} est déjà supprimé."
    de_DE: "{name} ist bereits gelöscht."
    pt_PT: "{name} já foi excluído."
    ru_RU: "{name} уже удалено."
    id_ID: "{name} sudah dihapus."
  - key: "Would you like to report {name}. Are you sure?"
    en_US: "Would you like to report {name}.\\n\\nAre you sure?"
    ja_JP: "{name}を通報します。\\n\\nよろしいでしょうか？"
    zh_CN: "报告{name}。\\n\\n您确定吗？"
    ko_KR: "보고서 {name}. \\n\\n 확실합니까?"
    es_ES: "¿Le gustaría reportar {name}?\\n\\n¿Está seguro?"
    fr_FR: "Voulez-vous signaler {name} ?\\n\\nÊtes-vous sûr ?"
    de_DE: "Möchten Sie {name} melden?\\n\\nSind Sie sicher?"
    pt_PT: "Você gostaria de denunciar {name}?\\n\\nTem certeza?"
    ru_RU: "Вы хотите сообщить о {name}?\\n\\nВы уверены?"
    id_ID: "Apakah Anda ingin melaporkan {name}?\\n\\nApakah Anda yakin?"
  - key: "Up to {count} count"
    en_US: "Up to {count}"
    ja_JP: "{count}個まで"
    zh_CN: "最多{count}"
    ko_KR: "{count}개까지"
    es_ES: "Hasta {count}"
    fr_FR: "Jusqu'à {count}"
    de_DE: "Bis zu {count}"
    pt_PT: "Até {count}"
    ru_RU: "До {count}"
    id_ID: "Hingga {count}"
  - key: "Up to {count} length"
    en_US: "Up to {count}"
    ja_JP: "{count}文字まで"
    zh_CN: "最多{count}字符"
    ko_KR: "최대 {count} 문자"
    es_ES: "Hasta {count} caracteres"
    fr_FR: "Jusqu'à {count} caractères"
    de_DE: "Bis zu {count} Zeichen"
    pt_PT: "Até {count} caracteres"
    ru_RU: "До {count} символов"
    id_ID: "Hingga {count} karakter"
  - key: "Back to {name}"
    en_US: "Back to {name}"
    ja_JP: "{name}に戻る"
    zh_CN: "返回{name}"
    ko_KR: "{name}로 돌아갑니다."
    es_ES: "Volver a {name}"
    fr_FR: "Retour à {name}"
    de_DE: "Zurück zu {name}"
    pt_PT: "Voltar para {name}"
    ru_RU: "Вернуться к {name}"
    id_ID: "Kembali ke {name}"
  - key: "Go to {name}"
    en_US: "Go to {name}"
    ja_JP: "{name}へ進む"
    zh_CN: "继续{name}"
    ko_KR: "{name}로 진행"
    es_ES: "Ir a {name}"
    fr_FR: "Aller à {name}"
    de_DE: "Gehe zu {name}"
    pt_PT: "Ir para {name}"
    ru_RU: "Перейти к {name}"
    id_ID: "Pergi ke {name}"
  - key: "{name} is loading..."
    en_US: "{name} is loading..."
    ja_JP: "{name}読み込み中..."
    zh_CN: "{name}正在加载..."
    ko_KR: "{name}님이 로드 중입니다..."
    es_ES: "{name} está cargando..."
    fr_FR: "{name} est en cours de chargement..."
    de_DE: "{name} wird geladen..."
    pt_PT: "{name} está carregando..."
    ru_RU: "{name} загружается..."
    id_ID: "{name} sedang memuat..."
  - key: "Register to {name}"
    en_US: "Register {name}"
    ja_JP: "{name}を登録"
    zh_CN: "注册{name}"
    ko_KR: "{name} 등록"
    es_ES: "Registrar {name}"
    fr_FR: "Enregistrer {name}"
    de_DE: "{name} registrieren"
    pt_PT: "Registrar {name}"
    ru_RU: "Зарегистрировать {name}"
    id_ID: "Daftar {name}"
  - key: "Release from {name}"
    en_US: "Release {name}"
    ja_JP: "{name}を解除"
    zh_CN: "删除{name}"
    ko_KR: "{name} 해제"
    es_ES: "Liberar {name}"
    fr_FR: "Libérer {name}"
    de_DE: "{name} freigeben"
    pt_PT: "Liberar {name}"
    ru_RU: "Освободить {name}"
    id_ID: "Lepaskan {name}"
  # Language
  - key: "English"
    en_US: "English"
    ja_JP: "英語"
    zh_CN: "英语"
    ko_KR: "영어"
    es_ES: "Inglés"
    fr_FR: "Anglais"
    de_DE: "Englisch"
    pt_PT: "Inglês"
    ru_RU: "Английский"
    id_ID: "Bahasa Inggris"
  - key: "Japanese"
    en_US: "Japanese"
    ja_JP: "日本語"
    zh_CN: "日本语"
    ko_KR: "일본어"
    es_ES: "Japonés"
    fr_FR: "Japonais"
    de_DE: "Japanisch"
    pt_PT: "Japonês"
    ru_RU: "Японский"
    id_ID: "Jepang"
  - key: "Chinese"
    en_US: "Chinese"
    ja_JP: "中国語"
    zh_CN: "中文"
    ko_KR: "중국어"
    es_ES: "Chino"
    fr_FR: "Chinois"
    de_DE: "Chinesisch"
    pt_PT: "Chinês"
    ru_RU: "Китайский"
    id_ID: "Cina"
  - key: "Korean"
    en_US: "Korean"
    ja_JP: "韓国語"
    zh_CN: "韩语"
    ko_KR: "한국어"
    es_ES: "Coreano"
    fr_FR: "Coréen"
    de_DE: "Koreanisch"
    pt_PT: "Coreano"
    ru_RU: "Корейский"
    id_ID: "Korea"
  - key: "Spanish"
    en_US: "Spanish"
    ja_JP: "スペイン語"
    zh_CN: "西班牙语"
    ko_KR: "스페인어"
    es_ES: "Español"
    fr_FR: "Espagnol"
    de_DE: "Spanisch"
    pt_PT: "Espanhol"
    ru_RU: "Испанский"
    id_ID: "Bahasa Spanyol"
  - key: "French"
    en_US: "French"
    ja_JP: "フランス語"
    zh_CN: "法语"
    ko_KR: "프랑스어"
    es_ES: "Francés"
    fr_FR: "Français"
    de_DE: "Französisch"
    pt_PT: "Francês"
    ru_RU: "Французский"
    id_ID: "Bahasa Perancis"
  - key: "German"
    en_US: "German"
    ja_JP: "ドイツ語"
    zh_CN: "德语"
    ko_KR: "독일어"
    es_ES: "Alemán"
    fr_FR: "Allemand"
    de_DE: "Deutsch"
    pt_PT: "Alemão"
    ru_RU: "Немецкий"
    id_ID: "Bahasa Jerman"
  - key: "Portuguese"
    en_US: "Portuguese"
    ja_JP: "ポルトガル語"
    zh_CN: "葡萄牙语"
    ko_KR: "포르투갈어"
    es_ES: "Portugués"
    fr_FR: "Portugais"
    de_DE: "Portugiesisch"
    pt_PT: "Português"
    ru_RU: "Португальский"
    id_ID: "Bahasa Portugis"
  - key: "Russian"
    en_US: "Russian"
    ja_JP: "ロシア語"
    zh_CN: "俄语"
    ko_KR: "러시아어"
    es_ES: "Ruso"
    fr_FR: "Russe"
    de_DE: "Russisch"
    pt_PT: "Russo"
    ru_RU: "Русский"
    id_ID: "Bahasa Rusia"
  - key: "Indonesian"
    en_US: "Indonesian"
    ja_JP: "インドネシア語"
    zh_CN: "印尼语"
    ko_KR: "인도네시아어"
    es_ES: "Indonesio"
    fr_FR: "Indonésien"
    de_DE: "Indonesisch"
    pt_PT: "Indonésio"
    ru_RU: "Индонезийский"
    id_ID: "Bahasa Indonesia"
  # DateTime
  - key: "Year"
    en_US: "year"
    ja_JP: "年"
    zh_CN: "年"
    ko_KR: "년도"
    es_ES: "año"
    fr_FR: "année"
    de_DE: "Jahr"
    pt_PT: "ano"
    ru_RU: "год"
    id_ID: "tahun"
  - key: "Years"
    en_US: "years"
    ja_JP: "年"
    zh_CN: "年"
    ko_KR: "년도"
    es_ES: "años"
    fr_FR: "années"
    de_DE: "Jahre"
    pt_PT: "anos"
    ru_RU: "годы"
    id_ID: "tahun"
  - key: "Month"
    en_US: "month"
    ja_JP: "月"
    zh_CN: "月"
    ko_KR: "월"
    es_ES: "mes"
    fr_FR: "mois"
    de_DE: "Monat"
    pt_PT: "mês"
    ru_RU: "месяц"
    id_ID: "bulan"
  - key: "Months"
    en_US: "months"
    ja_JP: "月"
    zh_CN: "月"
    ko_KR: "월"
    es_ES: "meses"
    fr_FR: "mois"
    de_DE: "Monate"
    pt_PT: "meses"
    ru_RU: "месяцы"
    id_ID: "bulan"
  - key: "Day"
    en_US: "day"
    ja_JP: "日"
    zh_CN: "天"
    ko_KR: "낮"
    es_ES: "día"
    fr_FR: "jour"
    de_DE: "Tag"
    pt_PT: "dia"
    ru_RU: "день"
    id_ID: "hari"
  - key: "Days"
    en_US: "days"
    ja_JP: "日"
    zh_CN: "天"
    ko_KR: "낮"
    es_ES: "días"
    fr_FR: "jours"
    de_DE: "Tage"
    pt_PT: "dias"
    ru_RU: "дни"
    id_ID: "hari"
  - key: "Week"
    en_US: "week"
    ja_JP: "週"
    zh_CN: "星期"
    ko_KR: "주"
    es_ES: "semana"
    fr_FR: "semaine"
    de_DE: "Woche"
    pt_PT: "semana"
    ru_RU: "неделя"
    id_ID: "minggu"
  - key: "Weeks"
    en_US: "weeks"
    ja_JP: "週"
    zh_CN: "星期"
    ko_KR: "주"
    es_ES: "semanas"
    fr_FR: "semaines"
    de_DE: "Wochen"
    pt_PT: "semanas"
    ru_RU: "недели"
    id_ID: "minggu"
  - key: "Hour"
    en_US: "hour"
    ja_JP: "時"
    zh_CN: "时间"
    ko_KR: "시간"
    es_ES: "hora"
    fr_FR: "heure"
    de_DE: "Stunde"
    pt_PT: "hora"
    ru_RU: "час"
    id_ID: "jam"
  - key: "Hours"
    en_US: "hours"
    ja_JP: "時"
    zh_CN: "时间"
    ko_KR: "시간"
    es_ES: "horas"
    fr_FR: "heures"
    de_DE: "Stunden"
    pt_PT: "horas"
    ru_RU: "часы"
    id_ID: "jam"
  - key: "Minute"
    en_US: "minute"
    ja_JP: "分"
    zh_CN: "部分"
    ko_KR: "부분"
    es_ES: "minuto"
    fr_FR: "minute"
    de_DE: "Minute"
    pt_PT: "minuto"
    ru_RU: "минута"
    id_ID: "menit"
  - key: "Minutes"
    en_US: "minutes"
    ja_JP: "分"
    zh_CN: "部分"
    ko_KR: "부분"
    es_ES: "minutos"
    fr_FR: "minutes"
    de_DE: "Minuten"
    pt_PT: "minutos"
    ru_RU: "минуты"
    id_ID: "menit"
  - key: "Second"
    en_US: "second"
    ja_JP: "秒"
    zh_CN: "第二"
    ko_KR: "두번째"
    es_ES: "segundo"
    fr_FR: "seconde"
    de_DE: "Sekunde"
    pt_PT: "segundo"
    ru_RU: "секунда"
    id_ID: "kedua"
  - key: "Seconds"
    en_US: "seconds"
    ja_JP: "秒"
    zh_CN: "第二"
    ko_KR: "두번째"
    es_ES: "segundos"
    fr_FR: "secondes"
    de_DE: "Sekunden"
    pt_PT: "segundos"
    ru_RU: "секунды"
    id_ID: "detik"
  - key: "{year} year"
    en_US: "{year} year"
    ja_JP: "{year}年"
    zh_CN: "{year}年"
    ko_KR: "{year} 년"
    es_ES: "{year} año"
    fr_FR: "{year} année"
    de_DE: "{year} Jahr"
    pt_PT: "{year} ano"
    ru_RU: "{year} год"
    id_ID: "{year} tahun"
  - key: "{year} years"
    en_US: "{year} years"
    ja_JP: "{year}年"
    zh_CN: "{year}年"
    ko_KR: "{year} 년"
    es_ES: "{year} año"
    fr_FR: "{year} année"
    de_DE: "{year} Jahr"
    pt_PT: "{year} ano"
    ru_RU: "{year} год"
    id_ID: "{year} tahun"
  - key: "{year} years old"
    en_US: "{year} years old"
    ja_JP: "{year}歳"
    zh_CN: "{year}岁"
    ko_KR: "{year}살"
    es_ES: "{year} años"
    fr_FR: "{year} ans"
    de_DE: "{year} Jahre alt"
    pt_PT: "{year} anos"
    ru_RU: "{year} лет"
    id_ID: "{year} tahun"
  - key: "{month} month"
    en_US: "{month} month"
    ja_JP: "{month}月"
    zh_CN: "{month}月亮"
    ko_KR: "{month} 달"
    es_ES: "{month} mes"
    fr_FR: "{month} mois"
    de_DE: "{month} Monat"
    pt_PT: "{month} mês"
    ru_RU: "{month} месяц"
    id_ID: "{month} bulan"
  - key: "{day} day"
    en_US: "{day} day"
    ja_JP: "{day}日"
    zh_CN: "{day}一天"
    ko_KR: "{day} 낮"
    es_ES: "{day} día"
    fr_FR: "{day} jour"
    de_DE: "{day} Tag"
    pt_PT: "{day} dia"
    ru_RU: "{day} день"
    id_ID: "{day} hari"
  - key: "{month} months"
    en_US: "{month} months"
    ja_JP: "{month}月"
    zh_CN: "{month}月亮"
    ko_KR: "{month} 달"
    es_ES: "{month} mes"
    fr_FR: "{month} mois"
    de_DE: "{month} Monat"
    pt_PT: "{month} mês"
    ru_RU: "{month} месяц"
    id_ID: "{month} bulan"
  - key: "{day} days"
    en_US: "{day} days"
    ja_JP: "{day}日"
    zh_CN: "{day}一天"
    ko_KR: "{day} 낮"
    es_ES: "{day} día"
    fr_FR: "{day} jour"
    de_DE: "{day} Tag"
    pt_PT: "{day} dia"
    ru_RU: "{day} день"
    id_ID: "{day} hari"
  - key: "{hour} hour"
    en_US: "{hour}"
    ja_JP: "{hour}時"
    zh_CN: "{hour}时间"
    ko_KR: "{hour} 시간"
    es_ES: "{hour} hora"
    fr_FR: "{hour} heure"
    de_DE: "{hour} Stunde"
    pt_PT: "{hour} hora"
    ru_RU: "{hour} час"
    id_ID: "{hour} jam"
  - key: "{minute} minute"
    en_US: "{minute}"
    ja_JP: "{minute}分"
    zh_CN: "{minute}部分"
    ko_KR: "{minute} 부분"
    es_ES: "{minute} minuto"
    fr_FR: "{minute} minute"
    de_DE: "{minute} Minute"
    pt_PT: "{minute} minuto"
    ru_RU: "{minute} минута"
    id_ID: "{minute} menit"
  - key: "{second} second"
    en_US: "{second}"
    ja_JP: "{second}秒"
    zh_CN: "{second}第二"
    ko_KR: "{second} 두번째"
    es_ES: "{second} segundo"
    fr_FR: "{second} seconde"
    de_DE: "{second} Sekunde"
    pt_PT: "{second} segundo"
    ru_RU: "{second} секунда"
    id_ID: "{second} detik"
  - key: "{hour} hours"
    en_US: "{hour} h"
    ja_JP: "{hour}時間"
    zh_CN: "{hour}时间"
    ko_KR: "{hour} 시간"
    es_ES: "{hour} horas"
    fr_FR: "{hour} heures"
    de_DE: "{hour} Stunden"
    pt_PT: "{hour} horas"
    ru_RU: "{hour} часов"
    id_ID: "{hour} jam"
  - key: "{minute} minutes"
    en_US: "{minute} m"
    ja_JP: "{minute}分"
    zh_CN: "{minute}部分"
    ko_KR: "{minute} 부분"
    es_ES: "{minute} minutos"
    fr_FR: "{minute} minutes"
    de_DE: "{minute} Minuten"
    pt_PT: "{minute} minutos"
    ru_RU: "{minute} минут"
    id_ID: "{minute} menit"
  - key: "{second} seconds"
    en_US: "{second} s"
    ja_JP: "{second}秒"
    zh_CN: "{second}第二"
    ko_KR: "{second} 두번째"
    es_ES: "{second} segundos"
    fr_FR: "{second} secondes"
    de_DE: "{second} Sekunden"
    pt_PT: "{second} segundos"
    ru_RU: "{second} секунд"
    id_ID: "{second} detik"
  - key: "Monday"
    en_US: "Monday"
    ja_JP: "月曜日"
    zh_CN: "星期 一"
    ko_KR: "월요일"
    es_ES: "Lunes"
    fr_FR: "Lundi"
    de_DE: "Montag"
    pt_PT: "Segunda-feira"
    ru_RU: "Понедельник"
    id_ID: "Senin"
  - key: "Tuesday"
    en_US: "Tuesday"
    ja_JP: "火曜日"
    zh_CN: "星期 二"
    ko_KR: "화요일"
    es_ES: "Martes"
    fr_FR: "Mardi"
    de_DE: "Dienstag"
    pt_PT: "Terça-feira"
    ru_RU: "Вторник"
    id_ID: "Selasa"
  - key: "Wednesday"
    en_US: "Wednesday"
    ja_JP: "水曜日"
    zh_CN: "星期 三"
    ko_KR: "수요일"
    es_ES: "Miércoles"
    fr_FR: "Mercredi"
    de_DE: "Mittwoch"
    pt_PT: "Quarta-feira"
    ru_RU: "Среда"
    id_ID: "Rabu"
  - key: "Thursday"
    en_US: "Thursday"
    ja_JP: "木曜日"
    zh_CN: "星期 四"
    ko_KR: "목요일"
    es_ES: "Jueves"
    fr_FR: "Jeudi"
    de_DE: "Donnerstag"
    pt_PT: "Quinta-feira"
    ru_RU: "Четверг"
    id_ID: "Kamis"
  - key: "Friday"
    en_US: "Friday"
    ja_JP: "金曜日"
    zh_CN: "星期 五"
    ko_KR: "금요일"
    es_ES: "Viernes"
    fr_FR: "Vendredi"
    de_DE: "Freitag"
    pt_PT: "Sexta-feira"
    ru_RU: "Пятница"
    id_ID: "Jumat"
  - key: "Saturday"
    en_US: "Saturday"
    ja_JP: "土曜日"
    zh_CN: "星期 六"
    ko_KR: "토요일"
    es_ES: "Sábado"
    fr_FR: "Samedi"
    de_DE: "Samstag"
    pt_PT: "Sábado"
    ru_RU: "Суббота"
    id_ID: "Sabtu"
  - key: "Sunday"
    en_US: "Sunday"
    ja_JP: "日曜日"
    zh_CN: "星期 天"
    ko_KR: "일요일"
    es_ES: "Domingo"
    fr_FR: "Dimanche"
    de_DE: "Sonntag"
    pt_PT: "Domingo"
    ru_RU: "Воскресенье"
    id_ID: "Minggu"
  - key: "Holiday"
    en_US: "Holiday"
    ja_JP: "祝日"
    zh_CN: "假期"
    ko_KR: "휴일"
    es_ES: "Feriado"
    fr_FR: "Vacances"
    de_DE: "Feiertag"
    pt_PT: "Feriado"
    ru_RU: "Праздник"
    id_ID: "Liburan"
  # Brand
  - key: "Google"
    en_US: "Google"
    ja_JP: "Google"
    zh_CN: "Google"
    ko_KR: "Google"
    es_ES: "Google"
    fr_FR: "Google"
    de_DE: "Google"
    pt_PT: "Google"
    ru_RU: "Google"
    id_ID: "Google"
  - key: "Apple"
    en_US: "Apple"
    ja_JP: "Apple"
    zh_CN: "Apple"
    ko_KR: "Apple"
    es_ES: "Apple"
    fr_FR: "Apple"
    de_DE: "Apple"
    pt_PT: "Apple"
    ru_RU: "Apple"
    id_ID: "Apple"
  - key: "Facebook"
    en_US: "Facebook"
    ja_JP: "Facebook"
    zh_CN: "Facebook"
    ko_KR: "Facebook"
    es_ES: "Facebook"
    fr_FR: "Facebook"
    de_DE: "Facebook"
    pt_PT: "Facebook"
    ru_RU: "Facebook"
    id_ID: "Facebook"
  - key: "Amazon"
    en_US: "Amazon"
    ja_JP: "Amazon"
    zh_CN: "Amazon"
    ko_KR: "Amazon"
    es_ES: "Amazon"
    fr_FR: "Amazon"
    de_DE: "Amazon"
    pt_PT: "Amazon"
    ru_RU: "Amazon"
    id_ID: "Amazon"
  - key: "Microsoft"
    en_US: "Microsoft"
    ja_JP: "Microsoft"
    zh_CN: "Microsoft"
    ko_KR: "Microsoft"
    es_ES: "Microsoft"
    fr_FR: "Microsoft"
    de_DE: "Microsoft"
    pt_PT: "Microsoft"
    ru_RU: "Microsoft"
    id_ID: "Microsoft"
  - key: "mathru.net"
    en_US: "mathru.net"
    ja_JP: "mathru.net"
    zh_CN: "mathru.net"
    ko_KR: "mathru.net"
    es_ES: "mathru.net"
    fr_FR: "mathru.net"
    de_DE: "mathru.net"
    pt_PT: "mathru.net"
    ru_RU: "mathru.net"
    id_ID: "mathru.net"
  # Apps
  - key: "There are {count} unread {obj}."
    en_US: "There are {count} unread {obj}."
    ja_JP: "{count}件の未読{obj}があります。"
    zh_CN: "{count}情况有一个未读的{obj}。"
    ko_KR: "{count} 사례의 읽지 않은 {obj}가 있습니다."
    es_ES: "Hay {count} {obj} no leídos."
    fr_FR: "Il y a {count} {obj} non lus."
    de_DE: "Es gibt {count} ungelesene {obj}."
    pt_PT: "Há {count} {obj} não lidos."
    ru_RU: "Есть {count} непрочитанных {obj}."
    id_ID: "Ada {count} {obj} yang belum dibaca."
  - key: "Copy to clipboard"
    en_US: "Copy to clipboard"
    ja_JP: "クリップボードにコピー"
    zh_CN: "复制到剪贴板"
    ko_KR: "클립 보드에 복사하십시오"
    es_ES: "Copiar al portapapeles"
    fr_FR: "Copier dans le presse-papiers"
    de_DE: "In die Zwischenablage kopieren"
    pt_PT: "Copiar para a área de transferência"
    ru_RU: "Скопировать в буфер обмена"
    id_ID: "Salin ke clipboard"
  - key: "Copied to clipboard"
    en_US: "Copied to clipboard"
    ja_JP: "クリップボードにコピーしました"
    zh_CN: "复制到剪贴板"
    ko_KR: "클립 보드에 복사하십시오"
    es_ES: "Copiado al portapapeles"
    fr_FR: "Copié dans le presse-papiers"
    de_DE: "In die Zwischenablage kopiert"
    pt_PT: "Copiado para a área de transferência"
    ru_RU: "Скопировано в буфер обмена"
    id_ID: "Disalin ke clipboard"
  - key: "Would you like to review the app?"
    en_US: "Would you like to review the app?"
    ja_JP: "アプリを評価してみませんか？"
    zh_CN: "您想评价该应用程序吗？"
    ko_KR: "앱을 평가해 보지 않겠습니까?"
    es_ES: "¿Te gustaría revisar la aplicación?"
    fr_FR: "Souhaitez-vous évaluer l'application ?"
    de_DE: "Möchten Sie die App bewerten?"
    pt_PT: "Gostaria de avaliar o aplicativo?"
    ru_RU: "Хотели бы вы оценить приложение?"
    id_ID: "Apakah Anda ingin meninjau aplikasi?"
  # Apps
  - key: "There are {count} unread {obj}."
    en_US: "There are {count} unread {obj}."
    ja_JP: "{count}件の未読{obj}があります。"
    zh_CN: "{count}情况有一个未读的{obj}。"
    ko_KR: "{count} 사례의 읽지 않은 {obj}가 있습니다."
    es_ES: "Hay {count} {obj} no leídos."
    fr_FR: "Il y a {count} {obj} non lus."
    de_DE: "Es gibt {count} ungelesene {obj}."
    pt_PT: "Há {count} {obj} não lidos."
    ru_RU: "Есть {count} непрочитанных {obj}."
    id_ID: "Ada {count} {obj} yang belum dibaca."
  - key: "Copy to clipboard"
    en_US: "Copy to clipboard"
    ja_JP: "クリップボードにコピー"
    zh_CN: "复制到剪贴板"
    ko_KR: "클립 보드에 복사하십시오"
    es_ES: "Copiar al portapapeles"
    fr_FR: "Copier dans le presse-papiers"
    de_DE: "In die Zwischenablage kopieren"
    pt_PT: "Copiar para a área de transferência"
    ru_RU: "Скопировать в буфер обмена"
    id_ID: "Salin ke clipboard"
  - key: "Would you like to review the app?"
    en_US: "Would you like to review the app?"
    ja_JP: "アプリを評価してみませんか？"
    zh_CN: "您想评价该应用程序吗？"
    ko_KR: "앱을 평가해 보지 않겠습니까?"
    es_ES: "¿Te gustaría revisar la aplicación?"
    fr_FR: "Souhaitez-vous évaluer l'application ?"
    de_DE: "Möchten Sie die App bewerten?"
    pt_PT: "Gostaria de avaliar o aplicativo?"
    ru_RU: "Хотели бы вы оценить приложение?"
    id_ID: "Apakah Anda ingin meninjau aplikasi?"
  - key: "Official website"
    en_US: "Official website"
    ja_JP: "公式サイト"
    zh_CN: "官方网站"
    ko_KR: "공식 사이트"
    es_ES: "Sitio web oficial"
    fr_FR: "Site officiel"
    de_DE: "Offizielle Website"
    pt_PT: "Site oficial"
    ru_RU: "Официальный сайт"
    id_ID: "Situs web resmi"
""";

/// Contents of localize.app.yaml.
///
/// localize.app.yamlの中身。
String appLocalizeYamlCode() => """
localize:
  # Apps
  - key: "AppTitle"
    en_US: "AppTitle"
    ja_JP: "アプリタイトル"
    zh_CN: "应用标题"
    ko_KR: "앱 제목"
    es_ES: "Título de la aplicación"
    fr_FR: "Titre de l'application"
    de_DE: "Anwendungstitel"
    pt_PT: "Título da aplicação"
    ru_RU: "Заголовок приложения"
    id_ID: "Judul aplikasi"
  - key: "SubTitle"
    en_US: "SubTitle"
    ja_JP: "サブタイトル"
    zh_CN: "字幕"
    ko_KR: "부제"
    es_ES: "Subtítulo"
    fr_FR: "Sous-titre"
    de_DE: "Untertitel"
    pt_PT: "Subtítulo"
    ru_RU: "Подзаголовок"
    id_ID: "Subjudul"
""";
