name: masamune_auth_google_firebase
description: Authentication plugin for Masamune that can implement Google sign-in on Firebase.
version: 3.1.0
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_auth_google_firebase

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^3.3.0
  masamune: ^3.5.0
  katana_auth_firebase: ^3.2.0
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1

dev_dependencies:
  test: ^1.25.0
  katana_test: ^3.1.0
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0

