// Dart imports:
import "dart:convert";
import "dart:io";

// Package imports:
import "package:yaml/yaml.dart";

// Project imports:
import "package:katana_cli/action/cloudflare/cloudflare_source_utils.dart";
import "package:katana_cli/katana_cli.dart";

/// Cloudflare initial configuration.
///
/// Cloudflareの初期設定を行います。
class CloudflareInitCliAction extends CliCommand with CliActionMixin {
  /// Cloudflare initial configuration.
  ///
  /// Cloudflareの初期設定を行います。
  const CloudflareInitCliAction();

  @override
  String get description =>
      "Initialize Cloudflare based on the information in `katana.yaml`. Also, make `wrangler` command available. `katana.yaml`の情報を元にCloudflareの初期設定を行います。また、`wrangler`のコマンドを利用可能にしてください。";

  @override
  bool checkEnabled(ExecContext context) {
    final cloudflare = context.yaml.getAsMap("cloudflare");
    final workers = cloudflare.getAsMap("workers");
    final enabledWorkers = workers.get("enable", false);
    final pages = cloudflare.getAsMap("pages");
    final enabledPages = pages.get("enable", false);
    return enabledWorkers || enabledPages;
  }

  /// 初期化済みのローカル設定と依存を、生成前に検証します。
  void validateLocal(ExecContext context) {
    for (final path in [
      "cloudflare/wrangler.jsonc",
      "cloudflare/.gitignore",
      if (isCloudflareRegionWorkerEnabled(context.yaml))
        "cloudflare/$cloudflareRegionWranglerConfig",
    ]) {
      if (!File(path).existsSync()) {
        throw StateError("--local に必要な初期設定がありません: $path。初期化の承認と実施が必要です。");
      }
    }
    if (context.yaml
        .getAsMap("cloudflare")
        .getAsMap("workers")
        .get("enable", false)) {
      validateLocalCloudflarePackages(const [
        "hono",
        "@mathrunet/masamune",
        "@mathrunet/masamune_cloudflare"
      ]);
      validateLocalFlutterDependencies(const ["masamune_functions_cloudflare"]);
    }
  }

  @override
  Future<void> exec(ExecContext context) async {
    if (isLocalApply) {
      validateLocal(context);
    }
    final bin = context.yaml.getAsMap("bin");
    final npm = bin.get("npm", "npm");
    final wrangler = bin.get("wrangler", "wrangler");
    final cloudflare = context.yaml.getAsMap("cloudflare");
    final workers = cloudflare.getAsMap("workers");
    final enabledWorkers = workers.get("enable", false);
    final enableFirebaseAuth = workers.get("enable_firebase_auth", false);
    final smartPlacement = workers.get("smart_placement", false);
    final enabledRegion = isCloudflareRegionWorkerEnabled(context.yaml);
    final regionPlacement = _placementRegion(
      workers.getAsMap("region")["placement"],
    );
    final rootRegionPlacement = _placementRegion(
      context.flavorContext?.yamlValue(
            const ["cloudflare", "workers", "region", "placement"],
            flavor: KatanaFlavor.prod,
          ) ??
          workers.getAsMap("region")["placement"],
    );
    final firebase = context.yaml.getAsMap("firebase");
    final firebaseProjectId = firebase.get("project_id", "");
    final pages = cloudflare.getAsMap("pages");
    final enabledPages = pages.get("enable", false);
    final pubspec = File("pubspec.yaml");
    final pubspecs = loadYaml(await pubspec.readAsString()) as Map;
    final projectIdFromPubspec = pubspecs.get("name", "");
    final projectIdFromYaml = cloudflare.get("project_id", "");
    final projectId =
        projectIdFromYaml.isEmpty ? projectIdFromPubspec : projectIdFromYaml;
    final rootProjectIdFromYaml = context.flavorContext?.yamlValue(
          const ["cloudflare", "project_id"],
          flavor: KatanaFlavor.prod,
        )?.toString() ??
        projectIdFromYaml;
    final rootProjectId = rootProjectIdFromYaml.isEmpty
        ? projectIdFromPubspec
        : rootProjectIdFromYaml;
    final flavor = context.flavorContext?.flavor.name ?? "prod";
    if ((enabledWorkers || enabledPages) && projectId.isEmpty) {
      error(
          "Project ID is not specified. Please enter [project_id] in `katana.yaml`.");
      return;
    }
    if (enableFirebaseAuth && firebaseProjectId.isEmpty) {
      error(
        "Firebase project ID is not specified. Please enter [project_id] in `katana.yaml`.",
      );
      return;
    }
    // Legacy entrypoint (also the file generated by `wrangler init`).
    final workerIndexFile = File(cloudflareLegacyEntryPath);
    final edgeEntryFile = File(cloudflareEdgeEntryPath);
    final regionEntryFile = File(cloudflareRegionEntryPath);
    final pagesIndexFile = File("cloudflare/public/index.html");
    final wranglerJsonc = File("cloudflare/wrangler.jsonc");
    final regionWranglerJsonc =
        File("cloudflare/$cloudflareRegionWranglerConfig");
    if (enabledRegion) {
      for (final name in ["$projectId-region", "$rootProjectId-region"]) {
        if (name.length > 63) {
          throw StateError(
            "The region Worker name `$name` exceeds 63 characters. Shorten [cloudflare]->[project_id]. "
            "region Worker名`$name`が63文字を超えています。[cloudflare]->[project_id]を短くしてください。",
          );
        }
      }
    }
    if (enabledWorkers) {
      // Existing projects used `src/index.ts`; move it to `src/edge.ts` first.
      await migrateCloudflareLegacyEntry();
    }
    final previousWranglerSource =
        wranglerJsonc.existsSync() ? await wranglerJsonc.readAsString() : null;
    final cloudflareDir = Directory("cloudflare");
    final workerRulesFile = File("cloudflare/src/rules.json");
    if (!cloudflareDir.existsSync()) {
      await cloudflareDir.create();
    }
    if (enabledWorkers || enabledPages) {
      if (!wranglerJsonc.existsSync()) {
        await command(
          "Initialize Cloudflare Workers",
          [wrangler, "init", projectId, "--yes", "--cwd=cloudflare"],
          runInShell: true,
        );
        // wranglerはcloudflare/{projectId}/配下にファイルを生成するため、cloudflare/直下に移動
        label("Rename files");
        final generatedDir = Directory("cloudflare/$projectId");
        await for (final entity
            in generatedDir.list(recursive: false, followLinks: false)) {
          final name = entity.path.split(Platform.pathSeparator).last;
          final targetPath = "${cloudflareDir.path}/$name";
          await entity.rename(targetPath);
        }
        await generatedDir.delete(recursive: true);
        await workerIndexFile.delete();
        await pagesIndexFile.delete();
      }
      label("Rewrite `.gitignore`.");
      final gitignore = File("cloudflare/.gitignore");
      if (!gitignore.existsSync()) {
        error("Cannot find `cloudflare/.gitignore`. Project is broken.");
        return;
      }
      final gitignores = await gitignore.readAsLines();
      if (context.yaml.getAsMap("git").get("ignore_secure_file", true)) {
        if (!gitignores.any((e) => e.startsWith("*-*-*.json"))) {
          gitignores.add("*-*-*.json");
        }
      } else {
        gitignores.removeWhere((e) => e.startsWith("*-*-*.json"));
      }
      await gitignore.writeAsString(gitignores.join("\n"));
    }

    if (enabledWorkers) {
      final functionsDir = Directory("cloudflare/src/functions");
      if (!functionsDir.existsSync()) {
        await functionsDir.create();
      }
      if (!edgeEntryFile.existsSync()) {
        await CloudflareWorkersEntryCliCode(
          entry: "edge",
          firebaseProjectId: enableFirebaseAuth ? firebaseProjectId : null,
        ).generateFile("edge.ts");
      }
      if (!workerRulesFile.existsSync()) {
        await const CloudflareWorkersRulesCliCode().generateFile("rules.json");
      }
      await CloudflareWranglerCliCode(
        projectId: rootProjectId,
        smartPlacement: smartPlacement,
      ).generateFile("wrangler.jsonc");
      final generatedWranglerSource = await wranglerJsonc.readAsString();
      // Existing Wrangler files are the source of truth. Rebuilding from the
      // template would discard routes, triggers, bindings, and other custom
      // root settings that Katana does not own.
      final restoredWranglerSource =
          previousWranglerSource ?? generatedWranglerSource;
      var synchronizedWranglerSource =
          WranglerEnvironmentSynchronizer.synchronize(
        restoredWranglerSource,
        flavor: flavor,
        workerName: projectId,
        rootWorkerName: rootProjectId,
      );
      if (enableFirebaseAuth) {
        synchronizedWranglerSource =
            WranglerEnvironmentSynchronizer.upsertVariables(
          synchronizedWranglerSource,
          flavor: flavor,
          values: {"FIREBASE_PROJECT_ID": firebaseProjectId},
        );
      }
      await wranglerJsonc.writeAsString(synchronizedWranglerSource);
      await installMissingCloudflarePackages(
        npm: npm,
        packages: const [
          "hono",
          "@mathrunet/masamune",
          "@mathrunet/masamune_cloudflare",
        ],
      );
      await addFlutterImport(
        [
          "masamune_functions_cloudflare",
        ],
      );
      if (enabledRegion) {
        await _applyRegionWorker(
          wrangler: wrangler,
          flavor: flavor,
          projectId: projectId,
          rootProjectId: rootProjectId,
          regionEntryFile: regionEntryFile,
          regionWranglerJsonc: regionWranglerJsonc,
          firebaseProjectId: enableFirebaseAuth ? firebaseProjectId : null,
          placement: regionPlacement,
          rootPlacement: rootRegionPlacement,
        );
      }
    }
    if (enabledPages) {
      if (!pagesIndexFile.existsSync()) {
        await const CloudflarePagesIndexCliCode().generateFile("index.html");
      }
    }
  }
}

/// Default placement region of the region Worker.
///
/// region Workerの既定のplacementリージョン。
const cloudflareDefaultRegionPlacement = "aws:us-east-1";

String _placementRegion(Object? value) {
  final text = value?.toString().trim() ?? "";
  return text.isEmpty ? cloudflareDefaultRegionPlacement : text;
}

/// Generates and synchronizes the region Worker (`cloudflare/src/region.ts` and
/// `cloudflare/wrangler.region.jsonc`), and creates the Worker on Cloudflare if needed.
///
/// region Worker（`cloudflare/src/region.ts`と`cloudflare/wrangler.region.jsonc`）を
/// 生成・同期し、必要に応じてCloudflare上にWorkerを作成します。
Future<void> _applyRegionWorker({
  required String wrangler,
  required String flavor,
  required String projectId,
  required String rootProjectId,
  required File regionEntryFile,
  required File regionWranglerJsonc,
  required String? firebaseProjectId,
  required String placement,
  required String rootPlacement,
}) async {
  if (!regionEntryFile.existsSync()) {
    await CloudflareWorkersEntryCliCode(
      entry: "region",
      firebaseProjectId: firebaseProjectId,
    ).generateFile("region.ts");
  }
  // Existing Wrangler files are the source of truth (same as the edge Worker).
  if (!regionWranglerJsonc.existsSync()) {
    await CloudflareWranglerCliCode(
      projectId: "$rootProjectId-region",
      main: "src/region.ts",
      placementRegion: rootPlacement,
      includeAssets: false,
    ).generateFile(cloudflareRegionWranglerConfig);
  }
  var source = WranglerEnvironmentSynchronizer.synchronize(
    await regionWranglerJsonc.readAsString(),
    flavor: flavor,
    workerName: "$projectId-region",
    rootWorkerName: "$rootProjectId-region",
  );
  if (firebaseProjectId != null) {
    source = WranglerEnvironmentSynchronizer.upsertVariables(
      source,
      flavor: flavor,
      values: {"FIREBASE_PROJECT_ID": firebaseProjectId},
    );
  }
  source = WranglerEnvironmentSynchronizer.upsertPlacementRegion(
    source,
    flavor: flavor,
    region: placement,
  );
  await regionWranglerJsonc.writeAsString(source);
  if (isLocalApply) {
    return;
  }
  // Create the region Worker only when it does not exist yet.
  final existing = await Process.run(
    wrangler,
    [
      "deployments",
      "list",
      "--json",
      "-c",
      cloudflareRegionWranglerConfig,
      "--env",
      flavor,
    ],
    workingDirectory: "cloudflare",
    runInShell: true,
  );
  if (existing.exitCode == 0) {
    return;
  }
  await command(
    "Create Cloudflare region Worker `$projectId-region`",
    [
      wrangler,
      "deploy",
      "-c",
      cloudflareRegionWranglerConfig,
      "--env",
      flavor,
    ],
    workingDirectory: "cloudflare",
    catchError: true,
    failOnStderr: false,
  );
}

/// Migrates the legacy Worker entrypoint `cloudflare/src/index.ts` to
/// `cloudflare/src/edge.ts` and rewrites `"main"` of `cloudflare/wrangler.jsonc`.
///
/// Throws [StateError] if both files exist. Returns true if the file was migrated.
///
/// 旧Workerエントリファイル`cloudflare/src/index.ts`を`cloudflare/src/edge.ts`に移行し、
/// `cloudflare/wrangler.jsonc`の`"main"`を書き換えます。
///
/// 両方のファイルが存在する場合は[StateError]を投げます。移行した場合はtrueを返します。
Future<bool> migrateCloudflareLegacyEntry() async {
  final legacy = File(cloudflareLegacyEntryPath);
  final edge = File(cloudflareEdgeEntryPath);
  if (!legacy.existsSync()) {
    return false;
  }
  if (edge.existsSync()) {
    throw StateError(
      "Both `$cloudflareLegacyEntryPath` and `$cloudflareEdgeEntryPath` exist. "
      "Merge `$cloudflareLegacyEntryPath` into `$cloudflareEdgeEntryPath` manually, delete it, and run `katana apply` again. "
      "`$cloudflareLegacyEntryPath`と`$cloudflareEdgeEntryPath`の両方が存在します。"
      "手動で`$cloudflareEdgeEntryPath`へ統合して`$cloudflareLegacyEntryPath`を削除後、再度`katana apply`を実行してください。",
    );
  }
  await legacy.rename(edge.path);
  final wrangler = File("cloudflare/wrangler.jsonc");
  if (wrangler.existsSync()) {
    final source = await wrangler.readAsString();
    final updated = source.replaceAll(
      RegExp(r'"main"\s*:\s*"src/index\.ts"'),
      '"main": "src/edge.ts"',
    );
    if (updated != source) {
      await wrangler.writeAsString(updated);
    }
  }
  label(
    "Migrated `$cloudflareLegacyEntryPath` to `$cloudflareEdgeEntryPath` and updated `main` in `cloudflare/wrangler.jsonc`.",
  );
  return true;
}

/// Cloudflare Workers entrypoint (`edge.ts` / `region.ts`) codebase.
///
/// Cloudflare Workersのエントリファイル（`edge.ts` / `region.ts`）のコードベース。
class CloudflareWorkersEntryCliCode extends CliCode {
  /// Cloudflare Workers entrypoint (`edge.ts` / `region.ts`) codebase.
  ///
  /// [entry] is `edge` or `region`.
  ///
  /// Cloudflare Workersのエントリファイル（`edge.ts` / `region.ts`）のコードベース。
  ///
  /// [entry]は`edge`または`region`です。
  const CloudflareWorkersEntryCliCode({
    required this.entry,
    this.firebaseProjectId,
  }) : assert(
          entry == "edge" || entry == "region",
          "entry must be edge or region.",
        );

  /// Entry name (`edge` or `region`). It is also passed to `m.deploy` as `type`.
  ///
  /// エントリ名（`edge`または`region`）。`m.deploy`の`type`にも渡されます。
  final String entry;

  /// Firebase project ID.
  /// This is required to enable Firebase Authentication.
  ///
  /// FirebaseのプロジェクトID。
  /// これを渡すとFirebase Authenticationを有効にします。
  final String? firebaseProjectId;

  @override
  String get name => entry;

  @override
  String get prefix => entry;

  @override
  String get directory => "cloudflare/src";

  @override
  String get description =>
      "Define the code for $entry.ts in Cloudflare Workers. Cloudflare Workersの$entry.tsのコードを定義します。";

  @override
  String import(String path, String baseName, String className) {
    return """
import * as m from "@mathrunet/masamune_cloudflare";
import rules from "./rules.json";
${firebaseProjectId != null ? 'import type { MiddlewareHandler } from "hono";' : ''}
""";
  }

  @override
  String header(String path, String baseName, String className) {
    return "";
  }

  @override
  String body(String path, String baseName, String className) {
    final comment = entry == "region"
        ? """
// Register functions for fixed-region backends such as TiDB.
// This Worker runs in the placement region set in `wrangler.region.jsonc`.
//
// TiDBなどの固定リージョンのバックエンド向け機能を登録してください。
// このWorkerは`wrangler.region.jsonc`で指定したplacementのリージョンで動作します。"""
        : """
// Define [m.Functions.xxxx] for the functions to be added to Workers.
//
// Workersに追加する機能を[m.Functions.xxxx]を定義してください。""";
    return """
$comment
${firebaseProjectId != null ? """
class EnvironmentFirebaseAuthAdapter extends m.WorkersAuthAdapterBase {
    build(): MiddlewareHandler {
        return async (context, next) => {
            const projectId = context.env?.FIREBASE_PROJECT_ID;
            if (typeof projectId !== "string" || !projectId) {
                return context.text("Firebase project is not configured.", 503);
            }
            return await new m.FirebaseAuthAdapter({ projectId }).build()(context, next);
        };
    }
}
""" : """"""}
export default m.deploy([
${firebaseProjectId != null ? """
], {
    type: "$entry",
    rules: rules as m.RulesConfig,
    auth: new EnvironmentFirebaseAuthAdapter(),
});
""" : """
], {
    type: "$entry",
    rules: rules as m.RulesConfig,
});
"""}
""";
  }
}

/// Cloudflare Pages index.html codebase.
///
/// Cloudflare Pagesのindex.htmlのコードベース。
class CloudflarePagesIndexCliCode extends CliCode {
  /// Cloudflare Pages index.html codebase.
  ///
  /// Cloudflare Pagesのindex.htmlのコードベース。
  const CloudflarePagesIndexCliCode();

  @override
  String get name => "index";

  @override
  String get prefix => "index";

  @override
  String get directory => "cloudflare/public";

  @override
  String get description =>
      "Define the code for index.html in Cloudflare Pages. Cloudflare Pagesのindex.htmlのコードを定義します。";

  @override
  String import(String path, String baseName, String className) {
    return """
""";
  }

  @override
  String header(String path, String baseName, String className) {
    return "";
  }

  @override
  String body(String path, String baseName, String className) {
    return r"""
<!doctype html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	</head>
	<body>
	</body>
</html>
""";
  }
}

/// Cloudflare Workers rules.json codebase.
///
/// Cloudflare Workersのrules.jsonのコードベース。
class CloudflareWorkersRulesCliCode extends CliCode {
  /// Cloudflare Workers rules.json codebase.
  ///
  /// Cloudflare Workersのrules.jsonのコードベース。
  const CloudflareWorkersRulesCliCode();

  @override
  String get name => "rules";

  @override
  String get prefix => "rules";

  @override
  String get directory => "cloudflare/src";

  @override
  String get description =>
      "Define the code for rules.json in Cloudflare Workers. Cloudflare Workersのrules.jsonのコードを定義します。";

  @override
  String import(String path, String baseName, String className) {
    return """
""";
  }

  @override
  String header(String path, String baseName, String className) {
    return "";
  }

  @override
  String body(String path, String baseName, String className) {
    return r"""
{
  "version": "1",
  "rules": {
    "database": {
    },
    "storage": {
    }
  }
}
""";
  }
}

/// Cloudflare Wrangler.jsonc codebase.
///
/// Cloudflare Wrangler.jsoncのコードベース。
class CloudflareWranglerCliCode extends CliCode {
  /// Cloudflare Wrangler.jsonc codebase.
  ///
  /// Cloudflare Wrangler.jsoncのコードベース。
  const CloudflareWranglerCliCode({
    required this.projectId,
    this.smartPlacement = false,
    this.main = "src/edge.ts",
    this.placementRegion,
    this.includeAssets = true,
  });

  /// Worker entrypoint relative to `cloudflare/`.
  ///
  /// `cloudflare/`からの相対パスで指定するWorkerのエントリファイル。
  final String main;

  /// Fixed placement region such as `aws:us-east-1`.
  /// If specified, Smart Placement settings are not output.
  ///
  /// `aws:us-east-1`などの固定placementリージョン。
  /// 指定した場合、Smart Placementの設定は出力されません。
  final String? placementRegion;

  /// Whether to output the static assets (`./public`) settings.
  ///
  /// 静的アセット（`./public`）の設定を出力するかどうか。
  final bool includeAssets;

  /// Project ID.
  /// This is required to set the project ID in wrangler.jsonc.
  ///
  /// CloudflareのプロジェクトID。
  /// wrangler.jsoncにプロジェクトIDを設定するために必要です。
  final String projectId;

  /// Whether to enable Cloudflare Workers Smart Placement.
  ///
  /// Cloudflare WorkersのSmart Placementを有効にするかどうか。
  final bool smartPlacement;

  @override
  String get name => "wrangler";

  @override
  String get prefix => "wrangler";

  @override
  String get directory => "cloudflare";

  @override
  String get description =>
      "Define the code for wrangler.jsonc in Cloudflare. Cloudflareのwrangler.jsoncのコードを定義します。";

  @override
  String import(String path, String baseName, String className) {
    return """
""";
  }

  @override
  String header(String path, String baseName, String className) {
    return "";
  }

  @override
  String body(String path, String baseName, String className) {
    return """
/**
 * For more details on how to configure Wrangler, refer to:
 * https://developers.cloudflare.com/workers/wrangler/configuration/
 */
{
	"\$schema": "node_modules/wrangler/config-schema.json",
	"name": "$projectId",
	"main": "$main",
	"compatibility_date": "2026-06-29",
	"compatibility_flags": [
		"nodejs_compat",
		"global_fetch_strictly_public"
	],${includeAssets ? """
	"assets": {
		// The path to the directory containing the `index.html` file to be served at `/`
		"directory": "./public"
	},""" : ""}
	"observability": {
		"logs": {
			"enabled": true,
			"invocation_logs": true
		},
		"traces": {
			"enabled": true
		}
	},
	"upload_source_maps": true,
	${placementRegion != null ? '"placement": { "region": ${jsonEncode(placementRegion)} },' : smartPlacement ? '"placement": { "mode": "smart" },' : '''
	/**
	 * Smart Placement
	 * https://developers.cloudflare.com/workers/configuration/smart-placement/#smart-placement
	 */
	// "placement": {  "mode": "smart" }'''}
	/**
	 * Bindings
	 * Bindings allow your Worker to interact with resources on the Cloudflare Developer Platform, including
	 * databases, object storage, AI inference, real-time communication and more.
	 * https://developers.cloudflare.com/workers/runtime-apis/bindings/
	 */
	/**
	 * Environment Variables
	 * https://developers.cloudflare.com/workers/wrangler/configuration/#environment-variables
	 * Note: Use secrets to store sensitive data.
	 * https://developers.cloudflare.com/workers/configuration/secrets/
	 */
	// "vars": {  "MY_VARIABLE": "production_value" }
	/**
	 * Service Bindings (communicate between multiple Workers)
	 * https://developers.cloudflare.com/workers/wrangler/configuration/#service-bindings
	 */
	// "services": [  {   "binding": "MY_SERVICE",   "service": "my-service"  } ]
}
""";
  }
}
