builders:
  masamune_model_docs_builder:
    import: 'package:masamune_model_docs_builder/masamune_model_docs_builder.dart'
    builder_factories: ['masamuneModelDocsBuilderFactory']
    build_extensions: {'.dart': []}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
targets:
  $default:
    builders:
      masamune_model_docs_builder:
        enabled: true
        generate_for:
          exclude:
            - test
            - example
            - ios
            - android
            - windows
            - macos
            - linux
            - web
          include:
            - test/integration/*
            - test/integration/**/*