name: masamune_auth_github_firebase
description: Authentication plugin for Masamune that can implement Github sign-in on Firebase.
version: 3.3.11
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_auth_github_firebase

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^3.2.1
  masamune: ^3.4.0
  katana_auth_firebase: ^3.1.8
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  shared_preferences: ^2.5.3

dev_dependencies:
  test: ^1.24.0
  katana_test: ^3.0.3
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0

