part of '/masamune_ai_openai.dart';

/// [FunctionsAction] to send OpenAI's ChatGPT queries from the server side.
///
/// OpenAIのChatGPTのクエリをサーバー側から送るための[FunctionsAction]。
///
/// {@macro functions_action}
class OpenaiChatGPTFunctionsAction
    extends FunctionsAction<List<OpenaiChatGPTFunctionsActionMessage>> {
  /// FunctionsAction] to send OpenAI's ChatGPT queries from the server side.
  ///
  /// OpenAIのChatGPTのクエリをサーバー側から送るための[FunctionsAction]。
  ///
  /// {@macro functions_action}
  const OpenaiChatGPTFunctionsAction({
    required this.messages,
    this.model = OpenaiAIModel.defaultModel,
  });

  /// All messages exchanged so far.
  ///
  /// これまでのやりとりすべてのメッセージ。
  final List<OpenaiChatGPTFunctionsActionMessage> messages;

  /// AI Model.
  ///
  /// AIのモデル。
  final OpenaiAIModel model;

  @override
  String get action => "openai_chat_gpt";

  @override
  DynamicMap? toMap() {
    return {
      "message": messages
          .map((e) => {
                "role": e.role._toOpenaiRoleLabel,
                "content": e.text,
              })
          .toList(),
      "model": model.name,
    };
  }

  @override
  List<OpenaiChatGPTFunctionsActionMessage> toResponse(DynamicMap map) {
    try {
      if (map.isEmpty) {
        throw Exception("Failed to get response from openai_chat_gpt.");
      }

      final choices = map.getAsList<DynamicMap>("choices");
      if (choices.isEmpty) {
        throw Exception("Failed to get response from openai_chat_gpt.");
      }

      final token = map.getAsMap("usage").get("total_tokens", 0);
      final message = choices.first.getAsMap("message");
      final role = message.get("role", "");
      final content = message.get("content", "");
      return [
        ...messages,
        OpenaiChatGPTFunctionsActionMessage(
          role: AIRole.values.firstWhereOrNull(
                  (item) => item._toOpenaiRoleLabel == role) ??
              AIRole.user,
          text: content,
          token: token,
        ),
      ];
    } catch (e) {
      debugPrint(e.toString());
      rethrow;
    }
  }
}

/// Message object used in [OpenaiChatGPTFunctionsAction].
///
/// The [role] contains the role of the message, [text] the content of the message, and [token] the number of tokens generated by the message.
///
/// [OpenaiChatGPTFunctionsAction]で利用するメッセージオブジェクト。
///
/// [role]にはメッセージの役割を、[text]にはメッセージの内容を、[token]にはメッセージで発生したトークンの数が入ります。
class OpenaiChatGPTFunctionsActionMessage extends FunctionsActionResponse {
  /// Message object used in [OpenaiChatGPTFunctionsAction].
  ///
  /// The [role] contains the role of the message, [text] the content of the message, and [token] the number of tokens generated by the message.
  ///
  /// [OpenaiChatGPTFunctionsAction]で利用するメッセージオブジェクト。
  ///
  /// [role]にはメッセージの役割を、[text]にはメッセージの内容を、[token]にはメッセージで発生したトークンの数が入ります。
  const OpenaiChatGPTFunctionsActionMessage({
    required this.role,
    required this.text,
    this.token,
  });

  /// Role of the message.
  ///
  /// メッセージの役割。
  final AIRole role;

  /// Message Content.
  ///
  /// メッセージの内容。
  final String text;

  /// Tokens generated through the use of ChatGPT.
  ///
  /// ChatGPTの利用で発生したトークン。
  ///
  /// See also:
  ///   * https://openai.com/pricing
  final int? token;
}
