name: katana_prefs_annotation
description: The annotation part of the package for type-safe use of retrieving and storing Shared Preferences values, defining data in a Freezed-like fashion.
version: 3.0.0-dev.0
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/katana_prefs_annotation

# TODO: Replace with your own license.
publish_to: none

environment:
  sdk: ">=3.5.0-0.0-dev <4.0.0"

dependencies:
  katana: ^3.0.0-dev.1
dev_dependencies:
  test: ^1.24.0
  katana_test: ^3.0.0-dev.0
  flutter_lints: ^4.0.0
  import_sorter: ^4.6.0
