name: katana_localization
description: A multilingual package that automatically creates code that can retrieve data from Google spreadsheets and write type-safe code with method chaining.
version: 3.0.12
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/katana_localization

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^3.2.1
  katana_localization_annotation: ^3.1.6
dev_dependencies:
  test: ^1.25.0
  katana_test: ^3.0.3
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0
