name: masamune_model_tidb_annotation
description: Define annotations that generate TiDB Data Service configuration from Masamune models.
version: 3.1.1
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_model_tidb_annotation

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  masamune_annotation: ^3.1.1

dev_dependencies:
  test: ^1.26.3
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0
