name: masamune_model_functions
description: A package for generating models for interacting with external databases and Firestore using Functions.
version: 3.3.0
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_model_functions

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta:
  katana: ^3.2.1
  masamune: ^3.4.0
  katana_functions: ^3.0.8
dev_dependencies:
  test: ^1.25.0
  katana_test: ^3.0.3
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0
  