name: masamune_animate
description: A package for animation that runs on the Masamune framework.
version: 3.0.29
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_animate

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^3.2.1
  masamune: ^3.4.0
dev_dependencies:
  test: ^1.25.0
  katana_test: ^3.0.3
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0
