name: katana_router
description: A package to automatically create routing configurations with build_runner to enable type-safe routing.
version: 3.1.10
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/katana_router

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^3.2.1
  katana_logger: ^3.0.10
  katana_router_annotation: ^3.0.8

dev_dependencies:
  test: ^1.25.0
  katana_test: ^3.0.3
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0
