name: katana_router
description: A package to automatically create routing configurations with build_runner to enable type-safe routing.
version: 3.0.0-dev.0
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/katana_router

# TODO: Replace with your own license.
publish_to: none

environment:
  sdk: ">=3.5.0-0.0-dev <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^3.0.0-dev.1
  katana_macro: ^3.0.0-dev.2
  katana_logger: ^3.0.0-dev.0
  katana_router_annotation: ^3.0.0-dev.0

dev_dependencies:
  test: ^1.24.0
  katana_test: ^3.0.0-dev.0
  flutter_lints: ^4.0.0
  import_sorter: ^4.6.0
