name: masamune_universal_ui
description: The package provide a universal UI that aims to be written in one code on any platform.
version: 3.2.0
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_universal_ui

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^3.3.0
  masamune: ^3.5.0
  url_launcher: ^6.3.1
  shimmer: ^3.0.0
dev_dependencies:
  test: ^1.25.0
  katana_test: ^3.1.0
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0
